### ISSUE TITLE
"Always Ask" for Default Category no longer working, it goes straight to a man-made category (not Default)

### ISSUE THREAD

**Issue by thesidejoe** [inorichi/tachiyomi#1022]
Pixel XL on Oreo 8.0.0
Tachiyomi version 0.6.3

https://gfycat.com/chiefimpressivegalapagostortoise

Whenever I bookmarked a new manga, it used to always ask which Category I wanted to put it in. Now, even with the Default category set to "always ask," it puts it in my only man-made category, "Finished." The only way to get it back into Default category is by selecting the manga, moving it, and unchecking "Finished." I was previously on version 0.6.1 when this was occurring, and I updated to 0.6.3 to see if it would fix, but it did not get fixed when I updated. The gif shows the process and the problem.

**Comment by CarlosEsco** [comment]
Yea i noticed this when i rewrote this portion in my pull request.  #960 .  If that does end up getting approved it will be fixed if not and @inorichi  rejects  I can look into this.

**Comment by LakotaGray** [comment]
The issue comes about due to you having created only 1 category. If you create an additional category, so you’d have default, finished, and “X” it will then return to standard operation. The best analogy I can give is that by only creating one category, Tachi assumes you want all manga added to library put into your created category. By creating 2+, it then seeks clarification and will default if none is given

**Comment by arkon** [comment]
I don't think this still happens.
