### ISSUE TITLE
Email protected shows up for every @ sign string

### ISSUE THREAD

**Issue by spiral6** [inorichi/tachiyomi#1053]
Some manga such as ["THE [email protected] - Million Live!!"](http://kissmanga.com/Manga/THE-iDOLM-STER-Million-Live)

should be written as THE iDOLM@STER MILLION LIVE. Is there an exception that we can set for this word, or can we rename manga in our library as a local database or something?

**Comment by ddmgy** [comment]
This is a Cloudflare feature called [email obfuscation](https://support.cloudflare.com/hc/en-us/articles/200170016-What-is-Email-Address-Obfuscation-), which blocks bots from scraping for emails. It would need to be disabled by the Kissmanga admins, which is unlikely to happen.

I do not think there is a way to trick Kissmanga or Cloudflare into thinking Tachiyomi is a normal user, either. Searching Kissmanga in a browser for "The iDOLM@STER" returns the correct names, but the page that Tachiyomi sees is already obfuscated.

**Comment by cylonu87** [comment]
The server return

`<a href="/Manga/THE-iDOLM-STER-Million-Live">THE <span class="__cf_email__" data-cfemail="94fdd0dbd8d9d4c7c0d1c6">[email&#160;protected]</span> - Million Live!</a>`

instead of

`<a href="/Manga/THE-iDOLM-STER-Million-Live">THE iDOL@MASTER - Million Live!</a>`

When the page is loaded, there is a javascript that will decode the value of data-cfemail and replace the span by the decoded value.

Here is a code I use to decode it:

```
String cfemail = "94fdd0dbd8d9d4c7c0d1c6";
StringBuilder sb = new StringBuilder();
try {
	int r = Integer.valueOf(cfemail.substring(0, 2), 16);
	for(int i = 2, j = cfemail.length(); i < j; i += 2) {
		char c = (char)(Integer.valueOf(cfemail.substring(i, i+2), 16) ^ r);
		sb.append(c);
	}
} catch(Exception e) {
}
System.out.println(sb.toString()); // iDOLM@STER
```

**Comment by CarlosEsco** [comment]
this can be closed.
