### ISSUE TITLE
[POLL] Bottom navigation

### ISSUE THREAD

**Issue by NoodleMage** [inorichi/tachiyomi#1110]
A lot of applications are migrating to bottom navigation. With the merging of latest manga in the new Catalogue Design we will have 5 (Library, Recently Update, Recently Read, Catalogue, Download) or 4 (download can be moved to settings) options for the bottom navigation.

We are curious what the community prefers. 

Please vote at:
http://www.strawpoll.me/14551866

**Note that the result of this poll will not be the deciding factor.**

**Comment by j2ghz** [comment]
Examples:
Side nav (current):
![](https://cdn.discordapp.com/attachments/358540894724554752/372676106555490304/Screenshot_2017-10-25-14-44-48-240_eu.kanade.tachiyomi.debug.png)
Bottom nav:
![](https://cdn-images-1.medium.com/max/1600/0*BAeNG5pwoO3Z-YDh.png)

I personally don't like bottom nav, because of the reduced screen space. Most of the time I only use library, so it doesn't make anything better for me.

**Comment by cd0rw0** [comment]
rather then moving download to the setting.
we can have 4 by merging library update & recently read in to 1 category "recents"
inside recents we can have 2 tab " library updates" & "recently read"
just an idea.

**Comment by NoodleMage** [comment]
Closing as enough people have voted.

Result:
No!: 67% (49 votes)
Yes! 26% (19 votes)
Don't care 7% (5 votes)
