### ISSUE TITLE
Download from mangahere always error due to ads on mangahere site in last page

### ISSUE THREAD

**Issue by SuperPenguin** [inorichi/tachiyomi#1121]
The number of pages on mangahere site is differs by 1 from tachiyomi app.
On mangahere site the last page is used for some kind of ads, and tachiyomi treat it as part of the chapter.
For example if a chapter have 40 pages in mangahere site + 1 page ads, tachiyomi will show it as 41 pages, and unable to load the last page.
Due to this, downloading any manga from mangahere always error.
I'm using version 0.6.6

**Comment by ddmgy** [comment]
Looks to be the same as #1050, which was fixed before 0.6.4. I'm not having any issue with extra pages in 0.6.6 or the dev version (r1301 currently); can you give any examples of manga that are showing this issue?

The code that generates the page list for Mangahere is [found here](https://github.com/inorichi/tachiyomi/blob/9ae6285eef2db68b348816b67ca7cd371117834e/app/src/main/java/eu/kanade/tachiyomi/source/online/english/Mangahere.kt#L185-L189), which contains a specific guard against the featured.html page (which contains the ads on the Mangahere website).

If you are running 0.6.6, the only thing I can think to do is go to Settings > Advanced > Clear chapter cache. This should clear the page lists that were grabbed from Mangahere, so when you go to download/read another chapter, it should grab the correct list.

**Comment by SuperPenguin** [comment]
https://www.mangahere.co/manga/isekai_yakkyoku/c001/
Here the chapter looks like in app
![Screenshot](https://i.imgur.com/hsmApxY.jpg)
All chapter from mangahere have same problem like this

**Comment by ddmgy** [comment]
That's odd, here is a screenshot of the same chapter on my device:

![screenshot_20171209-013104 1](https://user-images.githubusercontent.com/6520686/33793199-5297e2c8-dc81-11e7-8a1c-aee0e4c4fe65.png)

It's only 42 pages, so it's obviously not trying to load the advertisement page.

Do you have any Tachiyomi extensions installed? If you installed the Mangahere extension at some point, and never updated it, it would have this problem with loading the incorrect number of pages. Otherwise, I'm at a loss as to how your Tachiyomi is grabbing the extra page.

**Comment by SuperPenguin** [comment]
Ah, yes I still have old extension installed in my phone.
It's fixed now.

**Comment by ddmgy** [comment]
I'm glad it's been sorted out! You can go ahead and close this, then.
