### ISSUE TITLE
HTTP error 503 on KissManga

### ISSUE THREAD

**Issue by nicodemus88** [inorichi/tachiyomi#1165]
Hi, 

I have a problem accessing Kissmanga.com since yesterday. The error message is HTTP error 503. But I was able to access the website using a browser. 

Could you please check on this issue? 

Thank you for your time and assistance.

**Comment by Elkantar** [comment]
Hi, same issue here.

When using a Kissmanga hosted manga I got error 503 : service unavailable.

I switched all the manga I read on this database in order to avoid similar issues on Mangafox and Mangahere databases.

As I follow more than a hundred at the same time it'd be annoying to switch it to Mangasee/Mangahere as they don't use the same method to brodcast chapters.

Can you fix it as quickly as possible ?

Thanks in advance for your assistance.

**Comment by mmccoy37** [comment]
Same issue here with website KissManga. Tried opening in browser (within the app options) in case it was due to cloudflare DDOS protection, but that did not fix it.

**Comment by CarlosEsco** [comment]
issue is fixed but requires latest dev which is not released currently

**Comment by Elkantar** [comment]
When will ot be released ?

**Comment by StarStarGalactar** [comment]
Just wanted to chime in that I also have been having this issue.

**Comment by Elkantar** [comment]
According to CarlosEsco it was corrected in a new version that isn't released at the moment.
I hope It'd be released soon enough though...

**Comment by marianodato** [comment]
Same issue here!
When I'll the new version be released?

**Comment by LinkCable** [comment]
Last word from @inorichi was tomorrow, so just keep your eyes peeled.

**Comment by supernatant** [comment]
Same prob :(

**Comment by zbhoy** [comment]
Latest update fixes this issue. Please update and try again

**Comment by Elkantar** [comment]
Did you implement the new release on F-Droid ? I got mine apk from here.

**Comment by Elkantar** [comment]
Downloaded it from Github and it says that the new apk encountered a conflict with the apk from F-Droid (0.6.5) so I ought to backup my 247 manga library and state of reading manually, then uninstall Tachiyomi 0.6.5 (F-Droid version) and install the 0.6.7 apk from github.
It seems it work great except for the 13 errors it encountered while restoring my backup.

I saw that there was a 0.6.6... why is github depository so long to get the new updates ? That'd be convenient for the future to just have to install it once and then update it automatically..

**Comment by LinkCable** [comment]
The Github repo is the first to get updates. F-Droid is built off of the Github, and is now using the same signing key so there won't be the conflicts like you encountered going forward.

**Comment by j2ghz** [comment]
I think this is about fdroid.org, not fdroid.j2ghz.com

**Comment by Elkantar** [comment]
All I can say is that the apk from github was in conflict with the apk from the F-Droid app (en Android) even if there was 2 version between them.
I know that Github will always be the first up to date (I'm developper too) I was just wondering why it take so long for F-Droid to get your builds (the 0.6.5 has about a month on F-Droid and is the latest they got while it seems that you make 2 or 3 release per month).

**Comment by LinkCable** [comment]
Hmm it looks like the problem is the 0.6.6 build failed on F-droid. Hence why it wasn't uploaded. Not sure who handles this, @inorichi @NoodleMage do you know?

<img width="631" alt="screen shot 2018-01-09 at 6 59 37 pm" src="https://user-images.githubusercontent.com/620506/34749436-71b7a3da-f56f-11e7-8afb-83b645bfc676.png">

https://f-droid.org/wiki/page/eu.kanade.tachiyomi

**Comment by inorichi** [comment]
They usually had the build logs when it failed, but it's not the case now. 

About why it takes so long in F-Droid, I don't have the slightest clue. A few months ago all the builds were available within the next 2 days, so maybe they are having some internal issue. 

Sadly the guy I talked with when there were other issues is not there anymore: https://forum.f-droid.org/t/so-long-farewell-and-goodbye/600

To be honest, I'd like to drop official F-Droid support and roll only one release with many of the cool features Firebase provides, but I don't want to trouble people relying on their release.

If you're up for it, you can create an issue in their repo, they will surely be able to tell you more than me.

**Comment by Elkantar** [comment]
Ok thanks a lot though, Tachiyomi is a very useful app fore manga fan like me :)

**Comment by Johndeep** [comment]
Please don't drop F-Droid support, **or** please let us know how to keep Tachiyomi up to date beside through F-Droid without the need to manually visiting github regularly for update checking.
I somehow can understand why it can get annoying, if F-Droid is not that fast to be up to date or cannot even compile at all, worse if the update would fix a major problem already for us, who are relying on F-Droid _currently_.

I second this that Tachiyomi is a very useful and helpful app for keeping and maintaining the manga library with minimal hassle.

**Comment by CarlosEsco** [comment]
If you download the app from github you have option to click the version in about to check for updates and even have app autocheck for update

**Comment by Elkantar** [comment]
@CarlosEsco is right, I didn't have it on the 0.6.5 so I must always rely on F-Droid.
Btw, I asked F-Droid about that so I'll tell you when they answer and give you more details about that.

@Johndeep Don't Forget I don't think they'd do that, their app encountered more success 'till they put it on F-Droid repo simply because people like it when they don't have to check manually for updates and like having free scans without having to endure ads or mandatory premium subscribing.
If it stayed on Github, only some geeks like me who always check for new and interesting project would have known about this app and it'd be sad for all the Otaku that dreams about having all Mangafox, Mangahere, Kissmanga, Mangasee,etc... databases on their pocket :)

**Comment by LinkCable** [comment]
You can turn on automatic updates from the Github apk as well, fyi. @Johndeep @Elkantar 

Also we aren't responsible as to why F-Droid builds are failing.

![screenshot_20180110-170717](https://user-images.githubusercontent.com/620506/34798132-d752d336-f628-11e7-9aa2-a42f92897b09.png)

**Comment by Elkantar** [comment]
@LinkCable
I saw that in the options when CarlosEsco mentioned it but thanks btw.
As for F-Droid I know that you aren't responsible for the delay between the new release and the appearence on F-Droid, inorichi already told us about that.
I just contacted their support to get you some informations about why it takes so long :)

**Comment by Johndeep** [comment]
@LinkCable yes, I know the issue about F-Droid too, that is why it is so annoying, because (this case even without log) no one really knows what is happening and what or how it can be fixed (from developers point of view). (I cannot even access the forum of F-Droid right now)

But good to know that the github version has this additional extra, which is not included in the F-Droid version.

**Comment by robkooper** [comment]
The feature to check for updates does not seem to be enabled for the dev builds, is this only available for stable?

**Comment by j2ghz** [comment]
Yes, that is intentional @robkooper

**Comment by Hulkmaster** [comment]
Having this issue from yesterday

**Comment by Johndeep** [comment]
I don't want to be rude, but can the version 0.7.1 also be updated at f-droid please (the metafile is still at 0.7.0), I would be very grateful for that. ^^

**Comment by CarlosEsco** [comment]
Don't use fdroid. Especially if your using stable.

**Comment by Johndeep** [comment]
Huh, what did I miss? Don't use Fdroid in general or especially for Tachiyomi?

**Comment by CarlosEsco** [comment]
For tachiyomi. GitHub version of tachiyomi has a built it updater and as you see GitHub version gets updated first. Fdroid version it depends on fdroid itself to build the app.

**Comment by Johndeep** [comment]
Ah, that topic, well I guess that's a good point.

**Comment by null-dev** [comment]
@Johndeep basically F-Droid is super buggy and sometimes refuses to properly build the app when inorichi releases a new update (resulting in the update not showing up in F-Droid). Nothing we can do about it...
