### ISSUE TITLE
[Question] Did Tachiyomi just remove .yml support?

### ISSUE THREAD

**Issue by AMZMA** [inorichi/tachiyomi#1239]
I was just updated to Tachiyomi dev r1341 and I realise my .yml catalogues were gone.
Did Tachiyomi just remove .yml support?

I found it's too hard for me to understand how to build **tachiyomi-extensions** (may be someone would make proper guide via video or screenshot). And with those massive unreplied requests in tachiyomi-extensions, I doubt a new request will be heard.

I'm sorry if this sound rude.

**Comment by Skcyte** [comment]
I'm not trying to be mean but are they supporting .yml officially? (I hope staff/devs will clarify this)

Well it's kinda the requirements to build your own extension, you have to learn Kotlin and HTML/CSS stuff. I already have asked if there is a guide to write an extension. All they said just read and learn. 

To be clear if you want your source request to be made, you must have someone who interested to write such code and if only one person who requested it, it will become problem to the devs. Since they are working on this for free and in their spare time.

**Comment by NoodleMage** [comment]
Installing extensions is now added from within the application (dev version). No more building it yourself ;). 
Yaml are deprecated for over a year now.
