### ISSUE TITLE
source migration with old key-singed apk

### ISSUE THREAD

**Issue by drac0300** [inorichi/tachiyomi#1244]
Recently, the signing key of J2ghz’s f-droid repo changed, I still am running under a (dev) version signed with the old key (0.6.6-1304). Normally that wouldn’t be a problem, I’d just backup, uninstall, install the newest version and restore.
Except this time, according to https://github.com/inorichi/tachiyomi/issues/1225, by doing that, the app will be unable to restore all my manga from batoto. 
Which is why I ask, could you provide an apk of 6.8 signed with the old key, so that I’ll be able to migrate all my manga before reinstalling ?
Thanks in advance !

**Comment by null-dev** [comment]
If you have root, you can just copy the database.

**Comment by drac0300** [comment]
I do, is it the file /data/data/eu.kanade.tachiyomi.debug/databases/tachiyomi.db ?

**Comment by null-dev** [comment]
It is but actually nevermind. I don't think we want to risk losing data
here because with root there are issues with permissions and that could
cause problems...

**Comment by inorichi** [comment]
@j2ghz changed the debug key because he lost it (AFAIK), that's why I offered him mine if he was going to change it, so I doubt you'll ever get an updated compilation with that key.

Copying the database should be enough (the file you mentioned), I think I've done it before and I don't recall any permission issues. At most you'll have to `chown` the file to the user of the new installation.

I'll see if I can update the Batoto source to not fail during the recovery, but I think I won't be able to restore read chapters, just the library entry, category and tracking.

**Comment by drac0300** [comment]
I did that and it worked ! Many thanks for helping me (and also for developiing this great app by the way) !
