### ISSUE TITLE
[FEATURE REQUEST]display an overlay source on Library manga thumbnail, like download badges

### ISSUE THREAD

**Issue by nearbaskara** [inorichi/tachiyomi#1298]
**App version:**
r1370
**Issue/Request:**
allow thumbnail to have source overlay. 
like [this](https://i.imgur.com/X9JQzok.jpg) 
The reason why we need this is to make it easier when migrating or be able to know the difference between two manga with different sources but with the same titles.  

**Steps to reproduce (if applicable)**
[See picture](https://i.imgur.com/X9JQzok.jpg)
1. Just like download badges, you just need to check the option on display tab.

**Comment by LakotaGray** [comment]
You can already currently sort by source, which I do think would be beneficial if there was an indication of which source you were currently viewing when sorted that way. 
Instead of a thumbnail, on each title, since there's already downloaded badge and unread chapter badge, perhaps a horizontal line with the source name on or in it dividing the sections where a source begins and stops

**Comment by inorichi** [comment]
Merging with #1218. Even if the request is different the purpose is the same.
