### ISSUE TITLE
Old Dark Theme

### ISSUE THREAD

**Issue by sleey** [inorichi/tachiyomi#1302]
With the new update we lost the old dark theme, why not make a new option rather than replace the old one.
I think some people will prefer the old one, like me.

**Comment by dkanada** [comment]
I actually like the new dark theme, except for the new navigation bar color. It blends in with the background color and looks odd in my opinion. Usually I don't mind small changes to a vanilla material design look but I definitely think that the navigation bar, toolbar, and status bar should stay a shade darker for contrast. Lots of apps will also merge the toolbar and status bar into one large bar with the same color, which I also think looks odd.

**Comment by inorichi** [comment]
I don't mind a new theme 'Dark blue' to restore the old toolbar color. Open for pull request.

**Comment by InFlames03** [comment]
@dkanada I have an issue with that as the creator of the theme myself. It should be a simple fix, the chapter list background needs to be changed to a lighter shade instead of having it use the same colour as the navbar/status bar. I'd have fixed it already if I wasn't in the middle of my semester (and currently a week from finals)
