### ISSUE TITLE
[Feature Request] Download a chapter from another catalog when the main one fail

### ISSUE THREAD

**Issue by Nic007** [inorichi/tachiyomi#1388]
**App version:** 0.7.3

**Issue/Request:** Give an option to download a specific chapter from another catalog than the current mainn one.

**Other details:** When the download of a chapter fails, it is frequently because there is a problem with the current chapter in the Catalog. For example, you download the 300 chapters of a manga, but on these 300 chapters there's two of them which fails. If you go on the website, it will also fail for these chapters. 

When that happen you must add the manga from another source in your library and it's annoying to have twice the same manga if you really want everything available in offlinne. Maybe add an option to re-try the download from another source and "merge" it together?

**Comment by pervertkirito** [comment]
Ha, I think this guy on Discord also mention feature like that too

![](https://i.imgur.com/erBRkbZ.png)

**Comment by jogerj** [comment]
Since the chances of it happening is so small, here's what might work: Have the option only when the source fails to load ("error fail bla bla... would you like to fetch data from another source?") or from drop down menu of each chapter (download from alternative source). Then select manually which source, title, then which chapter (to prevent misnumbering). Tachiyomi marks the chapter with an asterisk or something (means this chapter was downloaded from a different source) then treats the whole chapter from the secondary source as if it was fetched from the original main source.

**Comment by edward-shen** [comment]
The chance of happening isn't small though; you need to account for issues when the user is in a spotty area or when there's just internet connectivity problems in general (e.g. downloading in a network where maybe a site is blocked).

Also, you'd likely require the user to select the manga from another source manually, in addition to the above. Consider the image that @pervertkirito attached; there's no good way to determine if the first source is equivalent to the second source, especially since the first one's title isn't localized while the second one is.

**Comment by inorichi** [comment]
Sorry but there are no plans to implement this at the moment. I know it's annoying when it happens but there's no easy way to add this.
