### ISSUE TITLE
Black borders are not cropped

### ISSUE THREAD

**Issue by Xeiniac** [inorichi/tachiyomi#1396]
**App version:** 0.7.2

**Issue/Request:** Black borders are not cropped

**Steps to reproduce (if applicable)**

 1. Open manga chapter page with black borders
 2. Use the crop borders feature 
 3. Black borders still remain

**Comment by bbtora** [comment]
Does this happen in the latest version (0.7.3) too?

**Comment by inorichi** [comment]
It's the expected behavior, the algorithm only looks for whiteish pixels.

If you have in mind a better implementation that works for both white and black borders, send a PR to https://github.com/inorichi/tachimage

I'm closing this issue since it doesn't belong to this repo, but feel free to create it on the other one.
