### ISSUE TITLE
[Feature Request] Use of SDcard on Android >= 5.0

### ISSUE THREAD

**Issue by FlinstoneJohn** [inorichi/tachiyomi#141]
Currently you can choose a folder to use for downloads. However, the downloads won't start and will be queued, in addition to failing to create a folder on the sdcard if you try. On <=5.0, the apps have to ask for sdcard permission. Tested on v0.1.3 on 5.0
![screenshot_2016-02-13-19-00-36](https://cloud.githubusercontent.com/assets/7767563/13030779/680f85b0-d284-11e5-972e-564c28208f6b.png)
![screenshot_2016-02-13-19-01-11](https://cloud.githubusercontent.com/assets/7767563/13030778/680e9ede-d284-11e5-9400-9581e18bc68a.png)

**Comment by FlinstoneJohn** [comment]
Also, can it be possible to, when you change the downloads folder, to move the previously downloaded files?

**Comment by inorichi** [comment]
Have you tried the debug version? It may be fixed already.

I don't want to move files. It's better to use some file manager for that. They are more consistent to errors.

**Comment by FlinstoneJohn** [comment]
Just tried it. No luck. Downloads towards the SD will be queued unless I change the location and kill the app.

**Comment by inorichi** [comment]
Well, I think I can't do anything about that. It seems third party apps can't write to the external SD Card on 4.4 and 5.0.

Write permissions are requested in the manifest of the app. If it still doesn't let you create a folder there, I'm afraid I can't do anything unless you root your device and modify the folder permissions to be writable by others.

I think Marshmallow should allow to write there with the runtime permissions (which are already requested in the app).

**Comment by HighOnCaffeine** [comment]
I found this will looking for a way to use the sdcard.
http://www.androidcentral.com/lollipop-brings-changes-way-your-sd-card-works-kind-youll
Don't know if its useful but I hope it is.

**Comment by dgel** [comment]
@inorichi On 4.4 access was severely restricted, Since 5.0 you need to use a particular API to ask the user for permission to read/write to external storage. There's two examples of how to do this on [stackoverflow](http://stackoverflow.com/questions/26744842/how-to-use-the-new-sd-card-access-api-presented-for-lollipop). I hope this is useful..

**Comment by inorichi** [comment]
If I understood this, I always have to use `Uri` to save the images instead of `File`, and in this case, I have to rewrite the download manager and probably also the view logic that loads the image. I may do it when I rewrite that part the manager in Kotlin.

**Comment by dgel** [comment]
Ok I checked out how other applications handle this, and the podcastaddict app only allows moving the downloaded files to one particular folder on the external sd card. It has a warning that since kitkat, android doesn't allow apps to write outside their own folder anymore. So I checked if I could make tachiyomi write to /storage/extSdCard/Android/data/eu.kanade.tachiyomi/files and it crashed after assigning the folder. However, the selection was persisted and I can download manga to that folder just fine.

So: perhaps make it so that on newer devices, you can only choose between internal storage and the SD card, with the SD card meaning this folder. It would be relatively easy and will fulfill 99% of the use cases I think =).

**Comment by inorichi** [comment]
Yup, that seems an easy fix. And I can also fix that crash.

**Comment by inorichi** [comment]
By the way, that folder will be deleted when the application is uninstalled, keep in mind you have to save them somewhere first if you don't want them to be deleted.

**Comment by dgel** [comment]
Ah thanks for the warning. Seems reasonable behaviour though

**Comment by inorichi** [comment]
The new directory selector now shows a list of folders. Try selecting one similar to `/storage/<external sd card>/Android/eu.kanade.tachiyomi.debug/files`.
