### ISSUE TITLE
Color banding issue

### ISSUE THREAD

**Issue by Deumiankio** [inorichi/tachiyomi#1416]
**App version:**
tachiyomi-dev 0.7.3-1411

**Issue:**
I've noticed an issue with color banding which is most apparent in background gradients.
The issue happens with all tested sources and also occurs when viewing local files.

Testing shows that the issue appears on multiple image formats (tested .jpg and .png) and with all selectable image decoders (Image, Rapid and Skia).
Custom color filter was disabled in each case.

![Color banding in Tachiyomi](https://i.imgur.com/d6wiedZ.jpg)

**Steps to reproduce**

View any image with color gradient in Tachiyomi (for example this gradient image from [here](https://imgur.com/a/CkGSz8R)).

**Other details:**

**Comment by inorichi** [comment]
Banding on the reader won't have a fix because they are decoded using RGB565 and using ARGB8888 is too memory aggresive, which leads to crashes due to out of memory errors.

Maybe this could be a setting on Android Oreo, because as of this version pixels are stored on the native heap so OOM errors are not problem. I'll keep it in mind but for now it won't be added.

**Comment by Deumiankio** [comment]
I can understand that in order to make the app usable on a large number of android devices with a multitude of different specs, some cutting of corners might be necessary.

However, AFAIK ARGB8888 approximately doubles the memory usage compared to RGB565.
On current-gen mobiles with 4GB+ RAM this increase is not a big price to pay for better picture quality.
(Even when reading large high-resolution chapters while downloading others in the background i've never seen tachiyomi use more than 500MB of memory).

I was curious to see how large the performance impact would be.
Seeing as Glide defaults to DecodeFormat.ARGB_8888 since v4, i tried changing the default RequestOptions in TachiGlideModule.kt to PREFER_ARGB_8888.
Unfortunately this did not change anything, presumably because of implied format conversions elsewhere (while downloading/downsampling/saving/cropping the images)?

Anyhow, the best way to approach this would probably be as you said, a setting with which you could switch between RGB565 and ARGB8888.
Then tachiyomi could be used by a large number of budget devices while providing better quality on devices that support a larger memory footprint.

I'm looking forward to seeing a feature like this in a future release.
Until then tachiyomi is still the best manga reader for Android for all series without gradients.
Thank you for creating it.

**Comment by inorichi** [comment]
> ARGB8888 approximately doubles the memory usage compared to RGB565.

Yes, as the numbers say it's 32 bit vs 16 bit per pixel.

> On current-gen mobiles with 4GB+ RAM this increase is not a big price to pay for better picture quality.

Actually it doesn't matter that your phone has 4GB+ RAM because each process has a limit on memory in the Java heap. With the `largeHeap=true` attribute in the manifest, tachiyomi can hold around 256MB of memory (it may be lower on low end devices). And I've seen a lot of out of memory crashes when the images were decoded as ARGB8888 in the past.

The only way to bypass this memory constraint is to use native memory, but sadly until Android 8.0, the `Bitmap` class holds a reference to the array of pixels, which means all the pixels take memory on the Java heap.

Btw the reader doesn't use Glide, that's why you won't notice any difference. Glide is used everywhere but the reader.

**Comment by yambadr** [comment]
@inorichi can we open this again? Android 8 has been out for a year and a bit. I've run into the [same issue](https://cdn.discordapp.com/attachments/349466829212876813/542802306102722580/Screenshot_20190206-221307_Tachiyomi.png).

Tachiyomi 0.8.0
Android 8.1

**Comment by Deumiankio** [comment]
@yambadr if you're not averse to patch and compile your own version of Tachiyomi for testing purposes you can fix this issue by directing the image view library to use ARGB8888 by inserting the line
`SubsamplingScaleImageView.setPreferredBitmapConfig(Bitmap.Config.ARGB_8888)`
anywhere before the SubsamplingScaleImageView to display the manga pages is created.

I'm running Android 9 on a Galaxy S8 and haven't noticed any issues with this change so far expect slightly choppier scrolling than in the unmodified app when flicking fast while viewing high-resolution images in webtoon mode.

Since poor performance with ARGB8888 is a problem with the library Tachiyomi uses to display pages, some drawback was to be expected (see [here](https://github.com/davemorrissey/subsampling-scale-image-view/issues/366).

**Comment by yambadr** [comment]
unfortunately I have no experience with compiling android apps, but thank you anyway
