### ISSUE TITLE
[Feature Request] Opening Tabs and Filters

### ISSUE THREAD

**Issue by shiloh960** [inorichi/tachiyomi#1423]
App version: 7.4

Request: When selecting a manga in my library, the manga automatically opens to the "Chapters" tab. It would be nice to have an option in settings for people who prefer the "Info" tab open. It can be especially helpful to people who are looking through their collections to decide which manga to read. Sure, it doesn't take that long to switch pages back and forth, it's just an extra step that would be nice to take out. Hope it's not too greedy of me.

Another thing: I have always wished for an app that includes something like folders an individual can name and select which mangas to place in them. Having the filters and folders option is so amazing!! I can't believe I finally found an app that has what I've been searching for! The filters for "unread" and "completed" are great. It would be even better to add filters for "ongoing" vs "completed" mangas, too. Of course, we wouldn't be able to keep two filters named "completed". How about "unread" and "finished"? Preferable not "unread" and "read", because I usually end up reading "read" in the present-tense.

I was also thinking that it would be great to have a filter while browsing in catalogues that filters out mangas that are already in my library. How's that sound?

Thanks for considering all this!

**Comment by jogerj** [comment]
1. It's already default for mangas not added to the library. If you already added it to the library, you'd want to view the next released chapter right away rather than the info page first anyway.
2. My Library > Menu ⋮ > Edit Categories
More advanced, you can choose in the settings which categories to download. e.g. You can make a category called "Downloaded" and then tag some of your mangas under this category, and then go to Settings > Downloads > Categories to include in download, check the category. Now only mangas in "Downloaded" category will be downloaded.
3. Mangas already added in your library (from the source you are viewing) are greyed out.
