### ISSUE TITLE
Download issue

### ISSUE THREAD

**Issue by SSa1nt** [inorichi/tachiyomi#1425]
**App version:0.7.4

**Issue/Request:Downloading Issue

I noticed that when you want to download a series like Berserk (in mangasee) that has chapters with the name -1,-2 etc but in the source it has 1,2,3** and then starts at 1 again, it doesnt download the other chapters, maybe because they have the same name?

Steps to reproduce (if applicable)

 1.Go to Catalogue, choose Mangasee
 2.Download Berserk
 3.Check downloaded chapters
(sorry for my english)

**Comment by jogerj** [comment]
Can confirm. The issue seems to be that there isn't any differentiating attributes between these chapters, so Tachiyomi assumes they are the same when downloaded.
http://mangaseeonline.us/read-online/Berserk-chapter-1-page-1.html
http://mangaseeonline.us/read-online/Berserk-chapter-1-index-2-page-1.html

If you look at other sources, each chapter is named differently.
For example: Kissmanga uses chapters 000a to 000p for the prologue chapters. Other sources uses full chapter title (I recommend these sources for any manga anyways)

However, not a big of an issue since it's a unique case that breaks it. Just use another source if it bothers you much.
