### ISSUE TITLE
[Feature-Request] Account-Based System

### ISSUE THREAD

**Issue by Daiichii** [inorichi/tachiyomi#1432]
Would it be possible to have account-based system like Mangarock? So that all the favourites and stuff can be backed up within the app and be restored via account when you log in?

**Comment by einstein95** [comment]
That would require having to pay for a cloud-based service to host the database. That is why other apps have ads or paid options.

**Comment by brassica77** [comment]
@and101 I found the Tachiyomi app among the backups for my stock Oneplus 5T.
But I recently installed LineageOS and in the newest backup there is no mention of Tachiyomi.
In the apps the settings are on Daily and default folder for backups.
Any idea how to enable backup for Tachiyomi?

**Comment by and101** [comment]
@brassica77 After flashing LineageOS, have you chosen to restore your Oneplus 5T backup during the initial set up? If so, then Tachiyomi will restore its backup once you install it using the APK. 

Keep in mind that Tachiyomi will not appear in the app restore list during initial set up since the app itself is not backed up, only its data and since Tachiyomi is not on the Play Store, it won't be automatically restored. As long as you restore from your OP5T backup, you simply have to install Tachiyomi using the APK. 

Also, to ensure that Google backup is enabled on LineageOS, ensure that in Settings > User & accounts > Google > Account sync > "App data" is enabled. 

You can also make sure backup is enabled from Google Drive. Open the app, from the slide menu select "Backups" > Then select the top-most backup (should be under "This device") > Tap on the cog icon on the top right > and then make sure "Back up to Google Drive" is enabled.

**Comment by brassica77** [comment]
It did restore during the initial setup after LineageOS install.
I just checked your suggestion and both options are activated, but in the first backup from one month ago, there are 46 apps listed, Tachiyomi included, and 36 apps listed in the recent one from LineageOS, without Tachiyomi.
I deleted the two backups now and I am waiting for the new backup to see if it includes Tachiyomi.

**Comment by and101** [comment]
In that case, it should pick up Tachiyomi for the next backup. On that note, the backup is normally initiated for an app if the its data has changed from the last backup. So in the future, once Tachiyomi is picked up again, you may see backups that are a few days old if you haven't used Tachiyomi during the following days, since there is no change to the data.

**Comment by brassica77** [comment]
Next backup doesn't contain Tachiyomi. In fact there are only playstore apps in there : all my non playstore apps are not backed up.
Any idea what's wrong?

**Comment by and101** [comment]
Are you checking from Google Drive? Apps not from the Play Store will only show up via the Google Drive app.

**Comment by Xalaxis** [comment]
When does it say your last backup was @brassica77 ?

**Comment by brassica77** [comment]
Today at 5:23 am CET.

**Comment by jogerj** [comment]
Your backup might have been corrupted/overwritten.
There's already an alternative (backup backup) with offline backup.

If you still lost your data, it is beyond our control.

**Comment by hamza-kun** [comment]
Hello,
Can we get automatic restore, this way we can set the automatic back up to a cloud storage and set the automatic restore to the same cloud storage. 
this will help us synchronize across devices.

**Comment by dhanjit** [comment]
Bumping this, because I can't seem to find "en.kanade.tachiyomi" int he backup/appdata folder in drive.

**Comment by and101** [comment]
If you have a PC and know how to use adb, try forcing the backup manually. The command is:

```
adb shell bmgr backupnow --all
```

**Comment by brassica77** [comment]
If this can help, I finally could enable Tachiyomi and other apps to be backep up in Drive by activating the Wifi and connecting the phone to a charger.

**Comment by arkon** [comment]
To address the original issue: no, there won't be an account-based system.
