### ISSUE TITLE
Category

### ISSUE THREAD

**Issue by fatimagrace015** [inorichi/tachiyomi#1437]
**Please fill out this form and remove the first two lines before posting.**
**If your issue is a request for a catalogue it belongs here https://github.com/inorichi/tachiyomi-extensions/**
**App version:**

**Issue/Request:**

**Steps to reproduce (if applicable)**

 1.
 2.
 3.

**Other details:**

**Comment by fatimagrace015** [comment]
What happened?! Fuck😂😂

Okay, here it is😂 i have ti category, default and shounen. Everytime I add a manga, it goes automatically at shounen even though I set the settings to always ask. Anyone who can help me?

App version 0.7.3.

**Comment by yambadr** [comment]
Please update to the latest version then confirm if the issue is still happening.

**Comment by inorichi** [comment]
You'll have to create another category. You can call it Default if you want to keep the same structure, and move every manga from the real "Default" to this new category, or just use it as a third category.

This happens because the "Default" category doesn't really exist and the app thinks there's only one category and automatically places it there.

**Comment by fatimagrace015** [comment]
I updated the app as you said, the categories are now okay but I cant
download....
