### ISSUE TITLE
My first time posting

### ISSUE THREAD

**Issue by Mioseque** [inorichi/tachiyomi#1443]
I just posted a webtoon about 10 minutes ago, and when me and my friends search it up it dosent show up,  when you search up my username it dosent show up either, it happens on computer and mobile, the only way i can access it is if i go into my dashboard, although it still have some views so that must mean some people have found it... im confused...

**Comment by CarlosEsco** [comment]
Where did you post?  Also this seems to be an extensions question not a tachiyomi issue

**Comment by Mioseque** [comment]
From my computer, because my phone won’t let me post it

**Comment by Mioseque** [comment]
Yeh XD

**Comment by CarlosEsco** [comment]
Please close

**Comment by Mioseque** [comment]
But I still don’t know the answer, so why should I close it

**Comment by Mioseque** [comment]
But ok I’ll close it

**Comment by null-dev** [comment]
@Mioseque Because this app has almost *nothing* to do with whatever website you are posting your webtoon on. The only thing in common with this app and webtoons.com is that this app is able to read webtoons from webtoons.com.

This app is not the webtoons.com official app. In fact, the owners of webtoons.com probably do not even know about this app.

Therefore, since this is an issue with webtoons.com (the website), and not this app, it should be closed.

**Comment by Mioseque** [comment]
It’s already closed get over it crybaby, go out and tell some other person who posted an issue that’s not about this specific app, I’m not responding since it’s c l o s e d now

**Comment by null-dev** [comment]
@Mioseque I'm just answering your question, I'm not trying to attack you or anything like that. We are here to help you but only about this app.

I'm trying to make sure that you get this issue resolved the right way, with the right people. I'm not sure why you are do angry but I'm just trying to help...

**Comment by Mioseque** [comment]
Yeh, I closed it, and I know you’re not trying to attack me, it’s just I’m pissed that when I closed it you told me to close it (don’t respond, I think you get my vibe rn and I’m getting way too many emails)
