### ISSUE TITLE
missing feature or search bugg

### ISSUE THREAD

**Issue by amboris** [inorichi/tachiyomi#1520]
**App version:**
v7.4 android 7.1.2
**Issue/Request:**
you cant search for author or tags on the all source search. 
trying to search that way gives zero result.
also in sources you need to type it in the drop down menu for the spesific type(searchbar for author, or klick on tag filter)
trying to search that way gives zero result.
its also not possible to find anything if you klick on the name of the author on the info tab from the manga. it uses the same global search but wont find any result, pls fix.
**Steps to reproduce (if applicable)**

 1. go to all sources
 2. klick to searchbar
 3. type name of author or tags you want to show

**Other details:**
would be wonderfull if we could have a unification search to search for name of manga, author and tags in one searchfunction. or fix the author search at info tab and you klick on the author name. and also pls make search possible if you klick on the tags it should search all manga on same source with that tag filter on.

**Comment by CarlosEsco** [comment]
What you want is not possible.  If the source itself doesn't offer the filtering, the extension can't either.

**Comment by amboris** [comment]
hm... i dont think you ever had tryed to use the search from source page else i do not know where you get that from. try to go to source website and type name, author or tag. this works on 90% of every source website.

**Comment by CarlosEsco** [comment]
Are you talking about general searching the author/tag or searching specifically by author/tag  as it two different things.  Some sources have a filter to allow filtering by a genre, some dont.

**Comment by LakotaGray** [comment]
No it’s not. It’s all based on what each source or site allows for search parameters. Some will search mangaka and title pieces in search. Some only do title. Some have genre filtering, while others don’t. Unfortunately There isn’t a universal search beyond basic title info. And for sites that don’t allow searching by genre or filtering by genres, it’s not possible to have Tachi do so for those sites. 

Unfortunately even the genre labeling isn’t always consistent. Some genres don’t appear on all sites, and some label differently. Which is why it’s all done site by site source by source

**Comment by DSeah17** [comment]
### I think there's definitely a search bug. To replicate it and see for yourself,

1. Go to catalogues
2. Search for Hirohiko
3. Only 1 manga comes out for the Manga Rock extension. Searching within that extension also only produces 1 result. (Shikei Shikkouchuu Datsugoku Shinkouchuu)
4. Going to MangaRock's own application and searching Hirohiko produces 14 results including all of the Jojo series.

**Comment by arkon** [comment]
This is heavily dependant on the extension's implementation of search, not the main app.
