### ISSUE TITLE
Loading Manga Library is slow

### ISSUE THREAD

**Issue by LuteFlute** [inorichi/tachiyomi#1559]
Basically im having a very similar if not exact same issue with the issue below as my manga is also downloaded onto my sd card. 

https://github.com/inorichi/tachiyomi/issues/1082

When tachiyomi is closed and i open it with downloaded badges checked, it takes a few seconds to load 2-4 seconds. If download badges is unchecked and you repeat the same procesc by closing tachiyomi as a background task and reopening it, loads almost instantly.

This started to happen right after i moved my downloaded manga to my class 10 sd card. 

Version 0.7.4

**Comment by paulo27ms** [comment]
How big is your library?

**Comment by LuteFlute** [comment]
My libraray was around 56 with around 25gb of space downloaded. So my library is huge. Sadly i moved it back to internal storage because it was becoming a hassle so i cant replicate the issue. Before I moved it i noticed it may be a problem of extensions as those are loading very slowly when you open tachiyomi.

**Comment by inorichi** [comment]
This happens when the `DocumentFile` API is used for downloads. It's only used when you choose a custom directory because Android don't let us write files with the old `File` API on other directories.

If you select the second or third option (it should point to your SD card), the `File` API will be used and it'll be fast, but the directory is something like `Android/data/<tachiyomi package name>/files`.

Sadly there's no way to optimize this lookup anymore (it's been way worse than 4s), and I plan to remove support for "Custom directory" and only allow to write on those `Android/data` directories with the `File` API, because besides being slow AF, I can't also load ZIPs or RARs using `DocumentFile`.
