### ISSUE TITLE
[Feature Request] Use latest unread manga chapter's cover for main cover page on library

### ISSUE THREAD

**Issue by selcukXIII** [inorichi/tachiyomi#1569]
Sometimes it is hard to keep track when there is so many chapters and all mangas have their first chapter's cover. An option to update this cover page automatically to latest chapters cover would be nice.

![screenshot_20180807-000902_tachiyomi](https://user-images.githubusercontent.com/8093503/43741190-30af8d4c-99d6-11e8-9d4f-6ecfe871b306.jpg)

**Comment by CarlosEsco** [comment]
This really wouldnt work on anything but comics.  Why not just set the cover yourself you want to update it?

**Comment by AmineI** [comment]
Adding my two cents here, right now the comic/manga source is the one to set the cover if I understood correctly. For example, the few series I follow on mangadex have the latest volume cover, while other sources don't. Using one of the tracking websites like MAL wouldn't work either since they also show the first volume as their cover. You may have better luck asking on your comics source website to refresh their covers, or searching for one that does, maybe ?
