### ISSUE TITLE
Taciyomi has stopped

### ISSUE THREAD

**Issue by P4RI4H** [inorichi/tachiyomi#1700]
**App version:**
0.8.0
**Issue/Request:**
Tachiyomi has stopped
**Steps to reproduce (if applicable)**

 1. Open app
 2.
 3.

**Other details:**
Force Stop doesnt fix it.
Restarting phone and clearing cache doesn't either.

https://i.imgur.com/suboqI3.jpg

Samsung Galaxy S9+

**Comment by Flat** [comment]
Can you post the relevant sections of `adb logcat > log.txt`? You'll need to install adb if you don't already but this will help us find the issue. You may also want to remove anything sensitive from the logs.

**Comment by P4RI4H** [comment]
Will do ASAP.

**Comment by P4RI4H** [comment]
Reinstalled app today and it fixed the issue. Will still post logs after I sort through for useful info and get rid of personal stuff.

**Comment by thiichico** [comment]
Thats is incredible, after 2 days the app works fine. I just test in another day and another and the problem was gone. The version didn't changed, but the start up problem did not appear anymore. I'll leave this comment if someone see the same issue, and my answer is just wait, the problem can be your phone. I think that could be closed. :)

**Comment by arkon** [comment]
Not enough info.
