### ISSUE TITLE
Restoring backup - Attempt to invoke virtual method

### ISSUE THREAD

**Issue by Wiles** [inorichi/tachiyomi#1778]
**App version:**
0.8.0

**Issue/Request:**

When I try to restore my backup most of the manga fail with the same error `Attempt to invoke virtual method 'org.jsoup.select.Elements org.jsoup.nodes.Element.select(java.lang.String)' on a null object reference`.

**Steps to reproduce (if applicable)**

 1. Attempt to restore backup

**Other details:**

[tachiyomi.log](https://github.com/inorichi/tachiyomi/files/2711087/tachiyomi.log)

[tachiyomi_2018-12-08_17-59.json.txt](https://github.com/inorichi/tachiyomi/files/2711088/tachiyomi_2018-12-08_17-59.json.txt)

**Comment by Flamingpineapplepie** [comment]
I looked around Google and it might be that your apk is corrupt? The key that is used for pulling up the backup information is returning null for you. This means that the restore string on your version of Tachiomi is searching for a keyword like... Title() Or some such thing and fails to find it. Because the title appearing in your backup doesn't match what the restore function is looking for... You don't get your manga updated. Try reinstalling tachiomi and restoring again? It may work.it may not. I am no developer so feel free to ignore me.

**Comment by Wiles** [comment]
I've tried reinstalling a couple times. I've also tried it on different Phones. A Nexus 4 running Lineage 15.1 and an Axon 7 running the stock ROM.

It looks like #1780 might be the same issue.

**Comment by arkon** [comment]
Sounds like the extension was broken.
