### ISSUE TITLE
UI problems

### ISSUE THREAD

**Issue by lleblansch** [inorichi/tachiyomi#1781]
**App version: 0.8.0**

**Issue/Request: Notification colors with substratum**

**Other details:**
If you get a chapter update notification the text is black, this is probably not a problem with substratum since all other apps work fine. I'm using a combination of swift dark and sai's oreo theme for my system wide dark mode, but tachiyomi doesn't seem to like it. I have had tachiyomi 0.7.4 debug for a while using sai's fresh substratum theme, with no problems. I don't have a lot of knowledge about android development so I don't know if this is fixable.

Here are screenshots of the notifications, and some from sync for comparison.

https://imgur.com/a/36uj5BZ

**Comment by Flamingpineapplepie** [comment]
As a community member I will state that it looks like a problem with your theme and not with Tachiomi. To put it simply: some applications have specific fonts that they use for notifications and your theme isn't able to alter the notification font because it isn't pointing to your system default font which comes in every color. The specified font is just one that is hard configured in the apk. I would make your "problem" into a request that they allow the notification bar to use the system default font instead of a hard-core one. I believe that there is a call for it, but in older versions of Android it wasn't available. So to keep Tachiomi "more accessible and functional" they kept hard-core font. Or,our devs here just weren't aware of that particular setting option for the font used for notifications and just haven't changed it because there really isn't that large of pull to do so.it isn't affecting most users and the rest of the app is still completely usable,yes? Not every single issue will be fixed and you can still just tap the notification bar to see what has updated. There is a perfectly usable workaround.

**Comment by inorichi** [comment]
The notifications of tachiyomi don't have any overriden font nor custom colors or whatever, it's a very simple notification.

The only place tachiyomi uses a custom font is in the library/catalog grid, to fit more text inside the cover.

**Comment by lleblansch** [comment]
Turns out I was using a light wallpaper which triggered the systemui default light mode/theme, that's why it looked weird
