### ISSUE TITLE
[Error 403]

### ISSUE THREAD

**Issue by nasijagungs** [inorichi/tachiyomi#1786]
[Error 403] on Mangarock source please fix it a.s.a.p happe today yesterday is okay

**Comment by AmineI** [comment]
So the first line of the text you deleted while creating this issue didn't ring a bell apparently ?

> **DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. 

The correct place to raise this "issue" is the [extensions repo](https://github.com/inorichi/tachiyomi-extensions/), go contribute there in a helpful manner. By the way, I don't have this issue so the problem is likely on your end.

**Comment by nasijagungs** [comment]
Okay sorry
