### ISSUE TITLE
[Bug] Double clicking a chapter will open 2 readers

### ISSUE THREAD

**Issue by Skcyte** [inorichi/tachiyomi#1851]
App version: r-1463
Issue:
Just a minor bug, when I accidentally double pressing a chapter it will open up 2 readers. Need to back up twice to back to chapter list.

**Comment by ReChinX** [comment]
I repeated the situation by fastly clicking a chapter twice, I think it may be fixed by adding a fast click checker global

**Comment by hXtreme** [comment]
I've also managed to do this, it mostly only happens when your phone's running a bit slow.

I don't know if this could be fixed, @neverfelly even if we have a fast click checker we could have the phone be substantially slow and allow for two instances of the reader to launch.

I think that its much easier to ignore than to fix it. If it does break something else like tracking or last read then it would be worth fixing this.

**Comment by metroid112** [comment]
Would it be possible to just limit the instances of the reader to 1? Unless that also brings other problems.

**Comment by hXtreme** [comment]
I'm not sure if there's any straight forward way to do it.

Note: For anyone who's able to limit the number of instances to 1 please also check out https://github.com/inorichi/tachiyomi/pull/1933#issuecomment-476183865
