### ISSUE TITLE
[Feature Request] Page Blacklisting

### ISSUE THREAD

**Issue by duckyb** [inorichi/tachiyomi#1889]
**App version:** 0.8.1

**Issue/Request:** There is an issue with quite a few non-english mangas, where while the user is reading, there are interruption/annoying pages that tell the user something along the lines of: 
"Are you tired of interruptions? come read on our forum!"

My request is to let the user tap and hold on such page and "blacklist" it, to stop the same page from appearing again.

**Steps to reproduce (if applicable)**
One example is "The Promised Neverland", chapter 94, source Manga Eden (IT)
(note: this is *not* an extension issue!!!)

**Other details:**
I hope this isn't too much to ask, it would be an awesome feature in my opinion.
I can definitely live without it but I had to switch sources (read: language) because of this.

**Comment by arkon** [comment]
You could read on their forum to avoid that too. ;)

On a more serious note, the best option would indeed just be finding an alternate source, which you already have done so.

**Comment by hXtreme** [comment]
Looks like it's out of scope of this application as any filter would need at least on some level image recognition (aka. machine learning) which I believe is not something a Manga reading app should be doing.

If we do get an extensive extension support with v1.x then it seems like a fun exercise in ML to try to implement this.

Also, the reason why machine learning would be required is because otherwise if even one pixel is different each time then the interruptions will persist.

Agreeing with Arkon, the best solution is to switch to a different source/group.

However if you do want this exact group then open a request to add source on github.com/inorichi/tachiyomi-extensions

**Comment by duckyb** [comment]
> Also, the reason why machine learning would be required is because otherwise if even one pixel is different each time then the interruptions will persist.

The fact is, that all of the interruptions I've seen are the exact same image, pixel for pixel. So it shouldn't be so hard to blacklist.

Switching sources is a solution, of course, but for people that read in their native language, in this particular case me reading in italian, switching sources means actually switching language entirely. And I would bet I'm not the only person that finds switching language in the middle of a story a major inconvenience.

**Comment by hXtreme** [comment]
@duckyb usually when you turn to blocking something it turns into being an arms race that's the reason why ML would be required.

I guess the best way might just be adding the group's website to tachiyomi.

**Comment by arkon** [comment]
Don't think this is going to happen.
