### ISSUE TITLE
F-Droid has disabled Tachiyomi 0.8.1

### ISSUE THREAD

**Issue by oldnomad** [inorichi/tachiyomi#1894]
It seems that commit aeaf4d78f80d401109c939dfa6543c40661290d8 back from November broke building the application on F-Droid, see buildlog at https://f-droid.org/wiki/index.php?title=eu.kanade.tachiyomi/lastbuild_39

It seems that F-Droid only allows maven repos from a limited whitelist that doesn't include https://dl.bintray.com/inorichi/maven

As a result, F-Droid disabled Tachiyomi version 0.8.1.

**Comment by arkon** [comment]
We might want to just take it down from F-Droid entirely and point everybody to installing it from the APKs on GitHub.

@inorichi Were you the point of contact for the main F-Droid releases?

---

Link: https://f-droid.org/en/packages/eu.kanade.tachiyomi/

**Comment by inorichi** [comment]
Hmm yeah, I forgot it could cause problems with fdroid.

[This](https://github.com/inorichi/storio/tree/androidpersistence-sql) is the branch I had to upload to bintray because for some reason I couldn't get it to work with jitpack. Maybe it works now so if anyone wants to try it be my guest.

Note: it might be needed to add one line for each submodule (except the annotations processor ones and samples, because we don't use them)

**Comment by Steef435** [comment]
It doesn't work, probably related to https://github.com/jitpack/jitpack.io/issues/3436. As suggested in the thread, the install task indeed does not seem to generate libraries for the missing modules. I played with it for a few hours but it's all black magic to me. (java build systems are so complex..)

(for the ones that do get generated, implementing the processor submodules generates a lot of compileClasspath resolve errors, but the other ones seem to implement without a hitch; it's just that some of the necessary modules are not published in the first place)

**Comment by DitFranXX** [comment]
I just trying to fix `storio` JitPack builds (at DitFranXX/storio@80c0eb3e2d6d0a9190056aac1250ce18508408da) with JitPack Docs.
```
com.github.DitFranXX.storio:storio-common:androidpersistence-sql-v1.13.0-g80c0eb3-2
com.github.DitFranXX.storio:storio-common-annotations-processor:androidpersistence-sql-v1.13.0-g80c0eb3-2
com.github.DitFranXX.storio:storio-sqlite-annotations:androidpersistence-sql-v1.13.0-g80c0eb3-2
com.github.DitFranXX.storio:storio-content-resolver-annotations:androidpersistence-sql-v1.13.0-g80c0eb3-2
com.github.DitFranXX.storio:storio-content-resolver:androidpersistence-sql-v1.13.0-g80c0eb3-2
com.github.DitFranXX.storio:storio-content-resolver-annotations-processor:androidpersistence-sql-v1.13.0-g80c0eb3-2
com.github.DitFranXX.storio:storio-sqlite-annotations-processor:androidpersistence-sql-v1.13.0-g80c0eb3-2
com.github.DitFranXX.storio:storio-sqlite:androidpersistence-sql-v1.13.0-g80c0eb3-2
```

It seems ok but I dunno it is fixed since I'm (mainly) not java developer...

(A lot javadoc error)

**Comment by ciborge** [comment]
Can we hope seeing 0.8.1 coming to Fdroid anytime soon?

**Comment by CarlosEsco** [comment]
If you are using stable there is no reason not to use GitHub version as it has auto update

**Comment by MPThLee** [comment]
Maybe this is good for who can't uninstall current version (eg. Generated backup is invaild etc...)

**Comment by inorichi** [comment]
@DitFranXX , submit a PR to my branch if you have fixed it.

Btw, I don't care if javadocs are not generated for the project, I only need want the library's jar/aar.

**Comment by paronos** [comment]
I have already submitted a merge request that fix the build of Tachiyomi on F-Droid https://gitlab.com/fdroid/fdroiddata/merge_requests/4635 by using a jitpack build from https://github.com/paronos/storio.

If you plan to fix it upstream I may clone it since it is almost an hack
(to make it work `sed` is used to replace `implementation 'eu.kanade.storio:storio:1.13.0'` with `compile group: 'android.arch.persistence', name: 'db', version: '1.0.0'; implementation 'com.github.paronos.storio:storio-common:3503176951@aar'; implementation 'com.github.paronos.storio:storio-sqlite:3503176951@aar'`).

**Comment by DitFranXX** [comment]
@paronos It works and It's better than my branch. 
I think you can open a PR to inorichi's branch.

**Comment by paronos** [comment]
PR opened https://github.com/inorichi/storio/pull/2
I'm not sure it's really better than your branch, since the content of the two .aar is equal.

https://jitpack.io/com/github/paronos/storio/storio-common/3503176951/storio-common-3503176951.aar -> https://jitpack.io/com/github/DitFranXX/storio/common/162b4d3317/common-162b4d3317.aar

https://jitpack.io/com/github/paronos/storio/storio-sqlite/3503176951/storio-sqlite-3503176951.aar -> https://jitpack.io/com/github/DitFranXX/storio/sqlite/162b4d3317/sqlite-162b4d3317.aar

**Comment by inorichi** [comment]
Gradle still doesn't seem to like it.

Using `implementation 'com.github.inorichi:storio:8be19de'` returns 
```
ERROR: Unable to resolve dependency for ':app@standardDebug/compileClasspath': Could not resolve com.github.inorichi:common:8be19de.
Show Details
Affected Modules: app
```

I don't know why it's looking for a `common` package instead of `storio-common`.

I tried using the specific modules, but it also fails: 
```
implementation 'com.github.inorichi.storio:storio-common:8be19de'
implementation 'com.github.inorichi.storio:storio-sqlite:8be19de'
```

**Comment by paronos** [comment]
It works with:
```gradle
compile group: 'android.arch.persistence', name: 'db', version: '1.0.0'
implementation 'com.github.inorichi.storio:storio-common:8be19de@aar'
implementation 'com.github.inorichi.storio:storio-sqlite:8be19de@aar'
```

**Comment by inorichi** [comment]
Yep, that worked, thanks.
