### ISSUE TITLE
[REQUEST] Multiply Blending for Color Filter

### ISSUE THREAD

**Issue by sitalkio** [inorichi/tachiyomi#2002]
Just a quick request for the color filter.

Values like  R138 G44 B22 A126 now give this result:
https://i.imgur.com/6qq29Dw.jpg

It would be cool, instead of just applying a semi-transparent color, to use a multiply blend mode and preserve the original blacks like this:
https://i.imgur.com/bJOaqxt.jpg

**Comment by Deumiankio** [comment]
This seems like a good idea.

On older Android versions with rooted devices CF.Lumen used to work fine for this to customize system-wide color filters with various blend modes, but AFAIK there is no way to do this on generic un-rooted devices.
Most color filter apps use overlays similar to the color filter currently implemented in tachiyomi, since IIRC Android does not allow views blending over different contexts.

Allowing the user to configure the blend mode for the color filter allows for better customization as well as better image quality while using the color filter e.g. by preserving blacks as shown in the original post.

**Comment by sitalkio** [comment]
I don't know how is technically done in Android but a similar manga app on F-Droid (Mi Manga Nu) has currently such a filter feature that blends the overlay to preserve blacks.
Of course this it's not so important, personally I'll always use and prefer Tachiyomi over all the other apps, but would be quite a nice touch.

**Comment by Deumiankio** [comment]
The PR has been merged and the new blend modes will be available in the next release.
If you want to try it before that use the [dev version](http://tachiyomi.kanade.eu/latest).

Details and example images are in the linked PR.

To get an effect similar to your second image try "Burn / Darken" with R255 G0 B0 A100" (only available if you're on Android Pie or newer) or "Multiply" with R255 G150 B150 A255 (on all Android versions).

**Comment by sitalkio** [comment]
Thank you so much, it works great!
