### ISSUE TITLE
Error "Source Not Installed: <number>"

### ISSUE THREAD

**Issue by narfanar** [inorichi/tachiyomi#2006]
**App version:** 0.8.4

**Android version:** 4.4.4

**Issue/Request:** Uninstalled sources (after the latest update that removed old sources) show up as numbers in error messages, or not at all.

**Steps to reproduce (if applicable)**

 1. Try to update a title from a source that is not installed. It says something like: "Source not installed: 9".
2. Try to download chapters from a title from a source that is not installed. It doesn't error or say anything. Just does nothing.

**Comment by CarlosEsco** [comment]
Install extensions for sources you were using.

**Comment by narfanar** [comment]
That's... obvious. The issues are:
1. In some cases, no error is displayed but there _has_ been an error.
2. Sources are not named, but still kept track of in some way (an index is shown). This is a break from established behavior from a previous version. Either maintain an index->name table for error messages, or point to a table on the repo, for a couple versions of the app after the break was committed.

**Comment by CarlosEsco** [comment]
They are named. The problem is the name of the source is not stored on the manga only the id of the source. So if a source changes it's name it doesn't affect the manga.  If you read the changelog before updating you would have seen hey my sources are going to be uninstalled let see what ones I use before updating.   Also if you had been installing the extensions over the internal sources as been recommended for 6+ months you wouldn't have any issues

**Comment by CarlosEsco** [comment]
Also there's a table on discord faq

**Comment by arkon** [comment]
A goal on 1.0 is to have more meaningful source identifiers so it's not as confusing.
