### ISSUE TITLE
[Feature Request] Optimizations for e-ink devices

### ISSUE THREAD

**Issue by oddhap** [inorichi/tachiyomi#2056]
**App version:**
0.8.4
**Android version:**
6.0
**Issue/Request:**
I'm using Tachiyomi on my e-ink android reader (Likebook Mars). The app works great, but some of the animations makes it feel sluggish because of the low refresh rate of e-ink. Some items are hard to read due to theme colors

I suggest the following changes to make Tachiyomi great on e-ink devices:
1. Option to disable all animations
2. Option to enable static menu on the left side
3. E-ink theme. White background with black text. 

I uploaded a video demonstrating v0.8.4 of Tachiyomi on e-ink if that helps.
https://youtu.be/bLC5_IsEN_c

Thanks for a great application!

**Comment by hXtreme** [comment]
For the animations I'd recommend you to go to developer settings and turn off animations, this would fix this problem for all your apps. Or else you can turn off page transitions from the settings in the reader.

An e-ink theme sounds nice. I'm currently on super low data so I didn't check your video but I'm assuming that the light theme didn't work for you?

Harsh



From: oddhap
Sent: Thursday 30 May, 2:17 pm
Subject: [inorichi/tachiyomi] [Feature Request] Optimizations for e-ink devices (#2056)
To: inorichi/tachiyomi
Cc: Subscribed


App version:
0.8.4
Android version:
6.0
Issue/Request:
I'm using Tachiyomi on my e-ink android reader (Likebook Mars). The app works great, but some of the animations makes it feel sluggish because of the low refresh rate of e-ink. Some items are hard to read due to theme colors
I suggest the following changes to make Tachiyomi great on e-ink devices:
Option to disable all animationsOption to enable static menu on the left sideE-ink theme. White background with black text.
I uploaded a video demonstrating v0.8.4 of Tachiyomi on e-ink if that helps.
https://youtu.be/bLC5_IsEN_c
Thanks for a great application!

**Comment by rocketen** [comment]
I also recently got a likebook mars and the only problem I couldn't work around was bookmarking. As far as I can tell the only visual difference of a booked marked chapter was the text turing ight blue which doesn't result ina  visual change on a eink display. If there was a eink theme it would be better if bookmarking was instead signified by bold text or a darker background.

**Comment by hXtreme** [comment]
@rocketen I've made a new issue in response to your comment but instead of using bold text I'm suggesting an icon.

**Comment by eweso** [comment]
I am using the tachiyomi app on my Onyx Boox Note 2 and would appreciate an e-ink optimised theme, too. For a perfect user experience all background colors should be removed or replaced by white and all font colors should be black. 

The blue in the main theme results in invisible icons. Because of the background color of the app, the notification bar is also invisible. Attached you will see, how it looks on e-ink at the moment.

Thank you! :)

![IMG_20191213_203848](https://user-images.githubusercontent.com/6918714/70827065-bedd1700-1de8-11ea-8fcf-7b1318dfd5ba.jpg)

**Comment by swistak** [comment]
If possible I'd like to bump this issue.
Recent change from 8.5 to 9.2 made it practically impossible to see the "read" manga titles. The contrast is way to low in theme, and the titles are unreadable both in dark and light themes.

It'd be perfect to have a high-contrast variant of the themes, but at least adjust the font colors to the way they were. I'll attach photos tomorrow.

**Comment by de-odex** [comment]
@eweso hold  the app icon, then tap "Optimize", then disable whiten background

**Comment by arkon** [comment]
- Option to disable all animations

This should be a system level thing.

- Option to enable static menu on the left side

It's bottom nav now, so this doesn't apply. Scrolling might be a bit janky though.

- E-ink theme. White background with black text.

There's a pure white theme now.

- As far as I can tell the only visual difference of a booked marked chapter was the text turing ight blue which doesn't result ina visual change on a eink display.

Added icons for the next version.

- Recent change from 8.5 to 9.2 made it practically impossible to see the "read" manga titles.

This hasn't been addressed yet. Not sure if @de-odex 's suggestion helps with that? I could try bolding unread chapter names too, but I'm not sure if that's noticeable enough.

**Comment by swistak** [comment]
Thanks for the feeback Arkon.

The e-ink I have grayscale and will convert colors to grayscale quite well, so change to blue color results in text becoming quite bright and hard to read under artificial light.

There are also few issues related to fonts / DPI / size of the device. For example on 1872 x 1404px, 227ppi device that I have, bottom menu is very small in relation to everything else. Some fonts also seem to scale with DPI some do not.

I'll try to gather a bunch of screenshots to show the problematic areas on the e-ink displays.

**Comment by eweso** [comment]
> @eweso hold the app icon, then tap "Optimize", then disable whiten background

This problem was solved with the new layout of Tachiyomi version 0.9.x. It's a massive improvement! Thank you! 

However, I didn't disable "whiten background", because the black color of the header was causing ghosting while using the app.

**Comment by arkon** [comment]
Closing this since it's kind of old.

Please open new individual issues if there's still some poorly design parts.
