### ISSUE TITLE
Library Updates does not list mangas from some sources

### ISSUE THREAD

**Issue by SeriousMatters** [inorichi/tachiyomi#2089]
**App version:**
0.8.4

**Android version:**
6.0.1

**Issue/Request:**
Library Updates does not list chapters from Chinese sources even though those were downloaded just fine.  I have tested this with 3 sources: ManHuaGui, Manhuadui, Pufei
**Steps to reproduce (if applicable)**

 1. Add English source extensions. Add some English mangas to library
 2. Add Chinese source extensions. Add some Chinese mangas to library
 3. Go to Library Updates and pull down to trigger updates
 4. Both English and Chinese mangas are downloaded. But only English ones are listed on Library Updates.

**Other details:**
Note that Android system notification correctly show both English and Chinese chapters updated. 
Android system language: English
Tachiyomi Lanugage setting: System default

**Comment by hXtreme** [comment]
Did the Chinese manga actually have new chapters?

**Comment by SeriousMatters** [comment]
@hXtreme
yes.  the new chapters are downloaded and can be read.  Also, My Library shows a number on top left of those Chinese manga to indicate there are new chapters as expected. Everything works as expected except not appearing on Library Updates list

**Comment by scb261** [comment]
At first I thought that I can reproduce the same problem, but now that I tested it some more, it seems to be source specific, not language specific (related issues https://github.com/inorichi/tachiyomi-extensions/issues/4268 https://github.com/inorichi/tachiyomi-extensions/issues/760). All extensions mentioned here (ManHuaGui, Manhuadui, Pufei) also don't have upload date for each chapter.

Maybe use library update date instead of upload date when it's absent? I see two possible implementations:
1. When updating chapter list, if date of upload is absent, use current date as upload date. Most probably devs won't accept this solution since it'll deceive users and app, so I won't go into details here.
1. Add one more field to database that would keep date when each chapter was retrieved as new. Use this in *Updates* tab when upload date is missing. Chapters will show up in *Updates* tab under *Today* / *Yesterday* / *3 days ago* / etc., but the date won't be displayed in chapter list on manga info page. This one is a little harder to implement and I'm not sure about changing database structure.

**Comment by CarlosEsco** [comment]
@AriaMoradi  please add it
