### ISSUE TITLE
Need more efficient RAM management

### ISSUE THREAD

**Issue by athreya-deva** [inorichi/tachiyomi#2100]
**App version:** 0.8.4

**Android version:** 7.1.2

**Issue/Request:** Consumes huge chunk of RAM when used for long time(more than 1 hour) . Please make it more memory efficient.

**Steps to reproduce (if applicable)**

 1. Read more than 100 chapter
 2. RAM usage increases for every chapter
 3. 

![IMG_20190626_143248](https://user-images.githubusercontent.com/31921383/60166859-85572600-981f-11e9-8989-db2fd21ec574.jpg)

**Other details:**

**Comment by RYNAPU** [comment]
You might want to try to reinstall the app.and clear the cache/data(make a backup first). Tachiyomi only uses 17mb for me even with huge chapters (200 sometimes) and the most it uses is 59mb.

**Comment by inorichi** [comment]
It's not really about making it more efficient, but maybe some memory leak. I've tested it for a bit on the emulator and memory is always properly cleaned up.

However I've had the app running on my tablet for several days and it was around 600MB, and everything was in the native heap. The only thing that comes to mind is the image decoder library not freeing memory on certain circumstances (because as I said, with a bit of testing everything was ok). It could be related to some image formats (or not...).

Anyways, please comment if you can reliably find a way where it only increases.

**Comment by athreya-deva** [comment]
@inorichi 
**Sorry for my English**
 I had **locked**  the app to prevent it from my device's aggressive background clearing. I think maybe it might be the issue.

I'll reply once I verify unlocking it clears the problem
