### ISSUE TITLE
[Feature Request] Manually combine manga from different sources

### ISSUE THREAD

**Issue by aghebert** [inorichi/tachiyomi#2101]
**DO NOT OPEN ISSUES/REQUESTS RELATING TO EXTENSIONS/CATALOGUES IN THIS REPOSITORY. Open them at the following repository  https://github.com/inorichi/tachiyomi-extensions/**

In referencing request #886, I'd like to suggest a different approach to combining manga.
Allow us the option to manually combine manga from different sources.
To go further, I imagine that after combining the same manga from different sources, it would show a single instance of that manga in your Library. When the manga is opened it would allow you to select from which source you'd like to read from.
Is this doable?

**Comment by XavierSchiller** [comment]
Inorichi did say this would break the app, automatically or not. 

The effort to implement this would be tough, I believe.

**Comment by metroid112** [comment]
Everything's doable, whether its worth it or not its up to the ones that are coding to decide.

I would think of it as a new step when selecting a manga from your library, you'd open a "multi-entry" (Like a folder in the home screen?) manga in the library which would lead to a 2nd screen or pop up deciding which entry to choose (this would have to be a manual process because I can't think of a way of automatically matching manga that is accurate with all the quirks from each source), then it would take to the manga info page of the selected entry.

**Comment by CarlosEsco** [comment]
As stated before not gonna be implemented
