### ISSUE TITLE
[1.x] A "Tracker" Extension system idea

### ISSUE THREAD

**Issue by DitFranXX** [inorichi/tachiyomi#2187]
**App version:** 1.x

**Issue/Request:**

In `0.x`, _Tracker service_  things are coded on main app. 
If you want to get a _tracker_, You should update app.
Contrary, It may gets 'Unwanted _tracker_' just from new app update.

So, how about add a "Tracker" extension? It makes a extensible and easy to adding/deploying new tracker.

I know that it may causes security problem, as providing password to external(extension) app.
May restricting app certificate and no 'User trust' system will solve this.

**Comment by Moravuscz** [comment]
If I may, I'd like to see the possibility of having multiple trackers enabled at once. You already have to manually bind the tracker's ID to the source, would it be much more of a problem to have more than just one?

**Comment by CarlosEsco** [comment]
@moravucz you already can use multiple trackers

**Comment by Moravuscz** [comment]
> @moravucz you already can use multiple trackers

Wait... yeah, you're right, sorry... I just kinda forgot after transitioning from MAL to AniList (tfw MAL's API is still not done...) since I don't use anything else...

I was kinda thinking, since I prefer MangaDex as source, and they have their own following & tracking system, it would be nice to have it available, potentially even auto-linked or at least asked to link when adding a title from MangaDex to your library if you wish to link the tracking feature as well...

**Comment by arkon** [comment]
Adding/changing trackers doesn't happen too often, so I'm fine with leaving it within the app itself.

**Comment by arkon** [comment]
https://github.com/tachiyomiorg/android-app/issues/10
