### ISSUE TITLE
Mangadex: Gif playback

### ISSUE THREAD

**Issue by tcyrus** [inorichi/tachiyomi#2240]
When trying to read [Ijousha no Ai Vol. 2 Ch. 9 Pg. 10](https://mangadex.org/chapter/416287/10), the page shows a flashing message via gif which doesn't continually flash on the original site.

I'm not sure if this issue should be on this repo or the main repo, but I'm submitting it here since it's related to the Mangadex extension.

**Comment by happywillow0** [comment]
I think I figured out what is going on and have more info from a bit of testing. The image is a gif which enables multiple frame playback. 
The first frame is the "aggregate site" warning while the second frame is the normal image. 

This works when viewing normally because the gif is set not to loop (total guess but it doesn't loop in any other browser or viewer I tested so far)
A aggregate site will most likely rip the image and covert to a jpeg or png. If automated, it will pull the first frame which contains the warning. 

Meanwhile Tachiyomi and glide are looping the gif so it is constantly showing both frames. 

Is there any options to control gif loops and to turn them off or on? 
Or will a glide update follow the loop configuration flag set within the gif?

**Comment by tcyrus** [comment]
https://github.com/inorichi/tachiyomi/blob/25327342fbfe5fd1dbfb7c06246193f5a4dfcbed/app/build.gradle#L173-L176

Someone could try a glide update (latest version is [4.10.0](https://search.maven.org/artifact/com.github.bumptech.glide/glide/4.10.0/jar))

**Comment by Flat** [comment]
Animated GIF files contain the data for looping or lack thereof. The linked image is not set to loop and therefore shouldn't. Glide automatically looping it is actually breaking GIF specification (although animation and the NETSCAPE loop block is sort of unofficial to begin with). Just wanted to give some more information after looking at the file itself and other GIF decoders that behave correctly. Unfortunately I don't have access to my main PC currently so I can't look further into the Glide/Tachiyomi code for GIFs.

**Comment by arkon** [comment]
I think Neko has Glide updated so could check if the issue persists there.

This wouldn't be the first time I've run into a bug with Glide's GIF handling though. The spec for GIFs is pretty disgusting.

**Comment by CarlosEsco** [comment]
Neko has same issue

**Comment by tcyrus** [comment]
Has anyone tried upgrading Glide, or are there breaking changes.
