### ISSUE TITLE
Add Webview and Browser Options to Chapter List.

### ISSUE THREAD

**Issue by MercerBoi** [inorichi/tachiyomi#2300]
I suppose you could brand this as a QoL feature but this is just me being pedantic.

When you open a manga in your library, the default screen has always been the Chapter List. If any error with Cloudflare or the source itself turns up, you gotta go to the Info Page, and then use those options. Adding them to the Chapter List will make this process just a _little_ bit faster.

Disregard this if you will, it's just a nitpick after all. Peace!

**Comment by clarjon1** [comment]
This also would be nice in the catalogue list. Perhaps a long click to pop up a menu, or the three-dot menu to show that there are options, with the "Open in Webview" and "Open in External Browser" entries?  Would help for testing if a site is misbehaving due to an outage on their end or due to something needing fixed in Tachiyomi.

**Comment by arkon** [comment]
@clarjon1 That already exists in the catalogue's menu when you open it (in dev).

**Comment by clarjon1** [comment]
> 
> 
> @clarjon1 That already exists in the catalogue's menu when you open it (in dev).

Thanks for the heads up! Looks like I'm updating my install to a dev build shortly!

**Comment by arkon** [comment]
Unfortunately, I think this makes the most sense within the info page. I think adding it to the chapters tab's menu would over-clutter it.
