### ISSUE TITLE
CloudflareInterceptor - Challenge changed

### ISSUE THREAD

**Issue by happywillow0** [inorichi/tachiyomi#2344]
**App version:** dev r1532

**Android version:** 10

**Issue/Request:** CloudflareInterceptor challenge url may have changed from `chk_jschl` to `chl_jschl`
Quick Link: [CloudflareInterceptor.kt](https://github.com/inorichi/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/network/CloudflareInterceptor.kt)

**Steps to reproduce (if applicable)**

 1. Open any catalog source with Cloudflare DDOS protection enabled.
 2. Recieve java.lang.Exception: Challenge not found 

**Other details:**

Reported by https://github.com/inorichi/tachiyomi-extensions/issues/1828
Confirmed on KissManga 

If anyone else can double check but I'm not sure which other pages if any are current running an active ddos protection with automatic challenge. 

Unless I misread how the challenge url works.

**Comment by lokesh-krishna** [comment]
Also affects ReadComicOnline.  

**App Version:** 0.8.4  
**Android Version:** 10

**Comment by happywillow0** [comment]
I finally decided to build the main app myself and see what happens. I'm having trouble debuging because I don't know how cloudflare was presenting the challenge before. 

What I do know is that the action url has changed and behind the scenes, the method of may have changed as well. It is currently `POST` to the challenge url which if correct returns the correct payload.  

```
<form id="challenge-form" action="/?__cf_chl_jschl_tk__={challenge url}" method="POST" enctype="application/x-www-form-urlencoded">
`    <input type="hidden" name="r" value="{encoded value}"></input>`
    <input type="hidden" name="jschl_vc" value="{value}"/>
    <input type="hidden" name="pass" value="{value}"/>
    <input type="hidden" id="jschl-answer" name="jschl_answer"/>
  </form>
```

The reason we are not getting more complaints is that the current code is somewhat working although not well. For example, KissManga, and MangaKisa both fail to obtain the solutionURL and present the exception "Challenge not found". However, in the background, it was enough for the challenge to go though so if you hit retry or open the source again, it loads normally.

**Comment by SnakeDoc83** [comment]
>The reason we are not getting more complaints is that the current code is somewhat working 

I don't think all the sites using Cloudllare have changed to their new protocol; so that may be another reason.

**Comment by xp-1000** [comment]
Hello, 
Also affects japscan : https://www.japscan.co/

**Comment by clarjon1** [comment]
This issue has become more annoying in the past couple of weeks for me. I thought it was a sources issue and waited for individual sources to fix it, but it seems to be spreading even to new source modules.

In the past week, I've lost the ability to make a second attempt to clear the challenge, however it appears that this issue is propagating to more sources. My main source used, kissmanga, is definitely affected.

The web view also appears broken. Entering the web view shows the cloudflare logo for each page load, and various elements on the page that ends up loading shows the cloudflare challenge page as well. the CSS appears to be failing to load in the webview -- i'm suspecting that it's having the challenge happen as well. Going back and re-opening in web view results in the cloudflare check being repeated

The Open in External browser view works fine. It does a check, and then the page elements load in properly. Going back and re-opening in external browser skips the cloudflare check, as the cookie/check data appears to be properly cached.

i've attached screencaps of web view and external browser view. Let me know if there's additional data i can scrape, eg via logcat to help nail this down.
Webview: 
![image](https://user-images.githubusercontent.com/627845/72194104-5d559b80-33da-11ea-8b44-dc9ec98c4473.png)

External browser: 
![image](https://user-images.githubusercontent.com/627845/72194109-66466d00-33da-11ea-88f6-969c92216a42.png)

**Comment by corneadoug** [comment]
No news on this error?
I tried all the methods to bypass that were mentioned in different issues, but no luck.
The annoying part is that it also block the discovery of new chapters and auto-download.
Sadly I had a lot of favorites on kissmanga :(

**Comment by polydoo** [comment]
MangaKisa too

**Comment by TheWrightStuff1994** [comment]
Readcomiconline as well...

**Comment by happywillow0** [comment]
2537

**Comment by TheWrightStuff1994** [comment]
Now it says this...
![Screenshot_20200125201350](https://user-images.githubusercontent.com/7861649/73129723-0c37d100-3fb0-11ea-86bd-2ca7e30f66e8.jpg)

**Comment by SnakeDoc83** [comment]
@TheWrightStuff1994 Does it work if you tap retry?  What's your device and version of Android?

**Comment by randw0** [comment]
Same exception here. Tapping retry doesn't change anything. S10 running android 10

**Comment by happywillow0** [comment]
Are you able pass the cloudflare page via webview?

**Comment by randw0** [comment]
@happywillow0 yes, able to do that. Also tried bypassing in webview and retrying incase that would work again. It didn't

**Comment by TheWrightStuff1994** [comment]
Yes able to pass cloudflare in web view but page still looks strange and I go back and it still does that java.io.IOException:Failed to bypass Cloudflare even after multiple retrys

**Comment by SnakeDoc83** [comment]
@TheWrightStuff1994 You say your webview looks strange, can you post a screencap?

**Comment by pavan3999** [comment]
![Screenshot_20200128-224648](https://user-images.githubusercontent.com/23577468/73288039-43acb480-4220-11ea-993f-097856e81272.jpg)

**Comment by TheWrightStuff1994** [comment]
![Screenshot_20200128191436](https://user-images.githubusercontent.com/7861649/73319704-ca529900-4202-11ea-8f2d-69c0c83a3d16.jpg)

**Comment by happywillow0** [comment]
Check WebView implementation in the developer options. 
If you have a choice, try the other ones such as Chrome or the updated Android Webview.

**Comment by TheWrightStuff1994** [comment]
I have a kindle fire where can I change that?
