### ISSUE TITLE
[Feature Request] Integrated web browser.

### ISSUE THREAD

**Issue by quinnjet** [inorichi/tachiyomi#2359]
Not sure if this is already a part of the app, and I'm just not using it correctly, but I was wondering whether it would be possible to integrate a web browser into Tachiyomi. For sources like Mangago, that only allow reading through a browser. I think it would be really cool to have the ability of bookmarking manga, and having them all in one app.

**Comment by arkon** [comment]
There is a WebView/ways to open a browser for a manga, but maybe the idea here could be to offer a way to open something in a browser/WebView from the actual manga reader view, especially when there's a failure to load page(s)?

**Comment by quinnjet** [comment]
I was thinking more along the lines of an integrated tab with search capabilities or URL copy paste capabilities. The first screen grab is what Tachiyomi's webview currently looks like, the second is what I'm hoping could be added on. There are times when a certain manga may not be visible via the Tachiyomi search results or catalogues, but it is available on the website. However, I think it could be useful either way.
![SmartSelect_20191206-201218_Gallery](https://user-images.githubusercontent.com/39835558/70368160-cf2f4800-1864-11ea-8f31-339d567dabe4.jpg)

![SmartSelect_20191206-201201_Gallery](https://user-images.githubusercontent.com/39835558/70368155-c63e7680-1864-11ea-9f94-ea15259f74d2.jpg)

**Comment by RuthlessRuler** [comment]
Integrating Browser will more be like a bloat to the App as there are multiple sources for same manga and when you have to use Browser, just use a full browser like FF/Chrome instead for reading as they will a do lot better job. Adding and maintaing the browser would be quite a hassle too. So stick to webview for log in purposes and use the option (Open in Browser) for Others so that you can get URL of the manga..

**Comment by arkon** [comment]
Agreed, this seems out of scope.
