### ISSUE TITLE
[Feature Request] Preload Image/Chapter Setting

### ISSUE THREAD

**Issue by DayatXD** [inorichi/tachiyomi#2367]
### Why/User Benefit/User Problem
Preload Image is useful if user is low speed internet and if user want just load specific page without load any page

### What/Requirements
Its like MangaDex Feature, it will preload image depends on setting for example if i setting 1 preload it will load just 1 page/image and do not load other page except if i turn next page/image

**Comment by hXtreme** [comment]
Tachiyomi should already be fetching next images automatically even before you go on them (as long as it's from the same chapter) at least that's what my experience has been like.

**Comment by RuthlessRuler** [comment]
Tachi does auto fetch images when you start reading a chapter. But if you are still facing this issue, then you might wanna consider these options;

- Download the chapters manually/automatically and then read it.
- Switch to a different Source(Like Manga Rock is more better than MangaDex[Log in/register using web-view for better speed] in terms of load speed). 
It may also be possible that your current source is also giving you low bandwidth. (i.e: Suppose you get 150kbps as down speed generally, but due to server overload/throttling you may be getting 50-100 kbps only further slowing it down)
- Upgrade your Internet Speed

**Comment by DayatXD** [comment]
I mean its limit the preload if the setting limit 2 preload it will be 2 preload 2 image only, but as reading next page/image it will load 1 more image ahead so it not load all of it simultaneously

**Comment by DayatXD** [comment]
Another for Example is when you want reread older manga that have 200+ page/image but you just want see page of 162 and dont want to waste internet qouta, so we can set the limit preload to 1 page/image and it will just load the page of 162 if you jump to that page.

**Comment by Lindsor** [comment]
I didnt see this feature request so opened another one (now closed) my idea is actually to preload the next CHAPTER completely for smooth reading.

Heres my original feature request:

**Why/User Benefit/User Problem**

This will vastly increase the UX for users who are binge reading (like most of us).
Currently when reading in WebToon mode when you reach the end of the chapter the scrolling "locks" while the app downloads the next chapter.
This also happens on normal reading mode (non-webtoon) but its less noticeable.


**What/Requirements**

When you reach a new chapter while reading we should download the next chapter and preload the next chapters.
This will allow the user to never notice the app is loading a chapter since by the time they are done reading the next one is already available.

should most likely be configurable in the settings since some people read faster / have slower networks they can tweak it to what works for them

**Comment by RuthlessRuler** [comment]
@Lindsor I believe many users don't have access to blazing fast internet for this to be take place and then there could also be result of IP Banning Users due to too many requests at once. If you want that seamless experience just download all chapters and read or just queue the next few to download so when you start reading the rest are already done. No need to implement such things honestly.

If queueing, you could go like, download all chaps for New manga and start reading after 1st Has been downloaded for the experience you want. For rest mangas, as you update them you have an option to auto download new chapters in settings so the feature you request becomes completely useless.

**Comment by Lindsor** [comment]
@RuthlessRuler totally agree on the blazing fast internet point. That's why i added the <N> configuration but it could be more granular to also specify "next page" level as well, so it would be a user choice. And slow internet is actually more of an argument to implement this, if your internet is very slow you don't want to wait 10s every-time you reach the end of a chapter to get the next one.

As for IP banning if downloading 2 chapters (current + next) would result in IP banning then downloading entire manga (100+ chapters) would DEFINITELY result in banning.

Last sunday i read over 200 chapters of 2 mangas (catching up) and had a very annoying experience in-between chapters (which is what prompted this)

Also just as a side note (personal opinion here), I'm sure we're all aware but MangaRock is shutting down their app. Judging by the comments in a lot of issues there's a lot of users like me looking to the next app to migrate, this means there's going to be a lot of comparisons between apps coming up. If people bring their requests for their favorite parts of these other apps Tachiyomi can improve quite a lot.

**Comment by RuthlessRuler** [comment]
@Lindsor But You Can Just download it already and set it remove when Marked read. Done.... This will fix the problem of you not having much ROM.
Seriously, no need for parameters that are going to confuse the end users.

And about talk for reading chaps and getting banned, since you are new you don't know this but one time Tachi Had multiple download feature which had to be removed due to IP banning. Why? Cause you are basically requesting 2 Chaps at a time and this increases the overall server load. This can result in decrease in server response time for others and thus boom.. the people will ban you cause they have large audience who they can make money from by showing ads and us from whom they don't make a cent.

Anyways, seeing the long list of requests and bugs that are there which are more sensible I think this feature can be postponed to a lot later date directly (at least in my opinion) 

And as for last, MR was one of the best sources at least when it came to load speed. Others don't have their API has good as MR which makes it difficult in many ways.(many don't even have API)

**Comment by jscti** [comment]
Came here to make this same feature request as it is a bit annoying on slow sources.

auto preload next chapter only when reaching say 90% of the current chapter would be possible ?. That way no blocking loading should be noticed.

I don't think internet speed or download ratio is relevant in this case, it only speed up by a few seconds a loading that would be done either way

**Comment by Lindsor** [comment]
@RuthlessRuler  thanks for the background (in your paragraph2) i didnt know about that one.
Your solution mostly works for what i need.
Its still annoying that when i decide to start a new manga i have to download all chapters instead of a preload-on-read feature.

But if the decision is to not implement something like this im ok since its just a small annoyance.
But i still think its a better user experience to preload while reading.

**Comment by CarlosEsco** [comment]
Here's a very simple solution since this will probably not get implemented
1.  find a new manga you like favorite it
2.  go to chapter list and click download next 10.
3.  once first chapter is downloaded start reading.  
4.  after a chapter or two if you want to continue reading press the back button and then 3dot download however many you want
5.  profit

**Comment by DayatXD** [comment]
Why the hell you all suggested to download it first, its not about reading it easy if downloaded first, it is about to fast re read certain manga page without wasting so much time with stupid download.

**Comment by DayatXD** [comment]
Its not preload whole chapter, its about (preload image limit)

**Comment by arkon** [comment]
The app was already updated to better handle skipping to different pages.

I'd only consider a better chapter preloading/auto-downloading. Limiting page preloading sounds like it'll be more troublesome than it's worth.

**Comment by DayatXD** [comment]
![IMG_20200118_023451](https://user-images.githubusercontent.com/47524544/72636997-2fcb9d80-3958-11ea-8655-d58fcb46d88e.jpg)
You can try it yourself on mangadex

**Comment by DayatXD** [comment]
![Screenshot_2020-01-18-02-38-55-102_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/47524544/72637346-ff383380-3958-11ea-85b2-f8ceb265ea3a.jpg)

I waited 1 minute to load this last page, instead with preload limit feature on mangadex i can load it only 1-10 second

**Comment by arkon** [comment]
What version of the app are you using?

**Comment by DayatXD** [comment]
Dev build

**Comment by RuthlessRuler** [comment]
> @RuthlessRuler thanks for the background (in your paragraph2) i didnt know about that one.
> Your solution mostly works for what i need.
> Its still annoying that when i decide to start a new manga i have to download all chapters instead of a preload-on-read feature.
> 
> But if the decision is to not implement something like this im ok since its just a small annoyance.
> But i still think its a better user experience to preload while reading.

IDK what's the problem of Downloading? When you are reading the manga, you are downloading all the images which are cached in the same directory as normal downloads directory. When you set the toggle to auto remove chaos after marking them read, then the issue of storage should also disappear. For me this works better as there is no need to preload anything and doesn't ruin the experience of reading.

I get it why Preloading images might be helpful especially when you want to view a particular chapter but when ur reading anew manga/rereading the entire, I believe downloading it is better and gives butter smooth experience.

**Comment by Lindsor** [comment]
@RuthlessRuler  like i said im ok with the group decision since the download works for me.

Were getting down to personal preference
YOU believe downloading everything is a better user experience for yourself
I believe preloading is a better user experience for me
We are both correct

I'm a software developer too so i know the juggling between what I, as a developer, believe to be best vs what my customers believe to be best.

The truth of the matter is, if there are multiple customers requesting a feature then there might be merit in implementation, whether you see value in it or not.

I get multiple requests for features that i would NEVER use or want in my applications but in the end the end-user is the customer.

But again, downloading works for what i want so i'm ok with not implementing.

**Comment by CarlosEsco** [comment]
@dayatxd are you trying to imply setting the mangadex preload made tachiyomi load faster?

**Comment by DayatXD** [comment]
@CarlosEsco why not?

**Comment by CarlosEsco** [comment]
Cause it didn't. If there was a speed increase it's cause loading in the web browser made you get the okay from their ddos protection.  

Them loading images on their side has no direct effect on the API endpoint we call

**Comment by marcialcarrillo** [comment]
Would appreciate this feature as well, if we are already preloading images in a chapter is to have a smooth reading experience, breaking that flow when transitioning chapters ruins that.

**Comment by ElerTheMagnanimous** [comment]
Doesn't manga rock app have this?

**Comment by arkon** [comment]
App was updated to start preloading the next chapter once you reach the last 3 pages of the current chapter instead of the last, which should hopefully help mitigate the loading "speed" on slower connections.
