### ISSUE TITLE
[Bug] Download auto-resumes

### ISSUE THREAD

**Issue by hXtreme** [inorichi/tachiyomi#2411]
### Device information
* Tachiyomi version: r1570

## Steps to reproduce
1. Add something to download
2. Pause the download
3. Add something else to download

### Expected behavior
The new download should be queued and the the the queue should remain paused.

### Actual behavior
The download resumes automatically.

**Comment by CarlosEsco** [comment]
So look at code there is a parameter to autostart it defaults to true
libraryupdate job passes in false
recentChaptersPresenter  uses true
chapterPresenter uses true

I understand why the last two default to true.  If my download was empty and i want to read a chapter and i click download i want them to start right away.  at least most the time.  But if the queue already exists and is paused i guess you would not want it to start since you have it paused for a reason
