### ISSUE TITLE
Stopping backup restore causes loss of progress

### ISSUE THREAD

**Issue by joseph619** [inorichi/tachiyomi#2482]
### Device information
* Tachiyomi version: Dev
* Android version: 9

Currently in Tachiyomi, if a backup is stopped in the middle of restoring, it cancels completely and all progress it's lost, and we have to start over. This is a huge waste of time if the backup file is very big, and users aren't always have the time to restore everything in a single attempt.

Thus I am requesting a fix the bug so that all backups are restored upto what's shown on the progress bar, and not lose all progress when Stop is clicked and start over. When restore is resumed, backups will also resume from where it's left off.

If all users don't like this option by default, it could be added as a toggle under Backup menu.

**Comment by arkon** [comment]
Not exactly a bug, since I think it's working as intended. Can be considered an enhancement.

**Comment by joseph619** [comment]
I guess, I wanted to post as feature request but that didn't sound right (there was no enhancement option). This is a very big issue to people with huge libraries (500+ manga).

**Comment by RuthlessRuler** [comment]
I think we need a better way for Backing Up and Restoring Data. I have to use Titanium Backup For seamless backup and restore causes when restoring many times it stops in middle due to Device gets auto lock or some other reason and we have to restart the whole Damm restore. It's a huge PITA and I would sincerely request a better backup / restore which can then be further becked up to Drive for Seamless  moving from one device to another.
