### ISSUE TITLE
Missing pages

### ISSUE THREAD

**Issue by aeli2** [inorichi/tachiyomi#264]
When downloading chapters, many pages in each chapter fail to download and must be redownloaded individually as i read the chapter.  In the folder are files with 0.10kb size each instead of actual images.

This happens up to every other page with some chapters and it never happened before i changed over to v0.2.0 (previous 0.1.4)

Version: v0.2.0
Android 5.1

**Comment by inorichi** [comment]
I'm not sure the issue it's related to 0.2.0, it could have been a coincidence. Anyways, maybe the last commit has fixed it. I would need confirmation.

**Comment by aeli2** [comment]
It is still happening on r661

**Comment by aeli2** [comment]
http://i.imgur.com/zEiD1HP.jpg

**Comment by aeli2** [comment]
after some testing this only seems to be happening on mangahere.  some kind of site specific thing?

**Comment by scriptmode** [comment]
From experience I can say missing pages happens on all sites. 
I think the reason is the caching-system the sites are using.
Tachiyomi is accessing the pages directly, which can occasionally 
fails because the pages are still loaded from the backend. 

For me it often takes 20-30 seconds and several attempts, until a retry works,
IMHO the popularity/age of a manga and time of the day are also relevant factors
in that game.

It might be worth to take a look at other OpenSource-Mangareader like MangaWatcher,
to find out how they prevent such problems.

BTW It's good that we now have a 'Open in Browser'-button on failed pages. But for
some reasons it does not appear on every failed site. Also it would be better to access
the page through the website itself, and not via the direct url. Because in later case
you still have the problem that the file is not available at that point, and you can't
utilize the regular loading-system of the site either.

**Comment by inorichi** [comment]
@aeli2 Does deleting only a failed image and trying to download the chapter again fixes it? If not, could you upload somewhere the file "index.json"?

**Comment by inorichi** [comment]
Also please upload some of those 0.10kb images

**Comment by inorichi** [comment]
Nevermind, it should work fine now.

BTW, having only simultaneous download is always the best choice to avoid incomplete downloads. Use more slots only if it's totally needed.

**Comment by aeli2** [comment]
for what its worth, the 0.10kb images when opened in notepad contain this text:
```

<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>
```
