### ISSUE TITLE
[Feature Request] Ability to select a control method (poll users)

### ISSUE THREAD

**Issue by e-shl** [inorichi/tachiyomi#2652]
I know the opinion of the developer
![image](https://user-images.githubusercontent.com/35057681/75640256-31c29500-5c56-11ea-9d8c-b328660586d0.png)

But also I know that once we were given a vote / choice

![image](https://user-images.githubusercontent.com/35057681/75640353-9382ff00-5c56-11ea-8bbc-10794de271e2.png)

New poll https://www.strawpoll.me/19471262

@arkon do not close and listen to users!

**Comment by Jays2Kings** [comment]
It's not happening, I even tried to do have both bottom navigation and side drawer as an option and it's impossible to maintain.

There's a reason why there's 0 apps out there that has both versions of navigation as an option

**Comment by Flat** [comment]
With Android 10 and new navigation gestures the previous navigation is a pain to use. I also voted previously against bottom navigation however the design guidelines have changed and in my opinion it is much easier to use and unobtrusive. Either way this is very unlikely to change.

**Comment by arkon** [comment]
I don't actually remember the poll that you posted a screenshot of. 

1.x is also supposed to move to a bottom nav UX as well.

**Comment by Soitora** [comment]
There's a good list of reasons why the move to bottom navigation was made.
I'll list the first three on top of my head:
1. Not too clear for all users;
1. Quite difficult to get to with your finger, especially now with taller and wider devices.
1. You can’t see what’s hidden there at once.

Here's a quick list of articles with neuanced information:
- https://uxplanet.org/tab-bars-are-the-new-hamburger-menus-9138891e98f4
- https://medium.muz.li/3-good-reason-why-you-might-want-to-remove-that-hamburger-menu-from-your-product-69b9499ba7e2

For me especially the new bottom navigation has made it significantly more easy to navigate through sections, because I on my average hands and 6.4" phone can't reach the side-drawer without stretching my hand.

**Comment by rama982** [comment]
Well i get used with android new gesture with facebook app top navigation and twitter app bottom navigation, so no issue with new changes.

**Comment by BlueCat300** [comment]
I'm not sure if this will be changed, but I think the bottom navigation is more for portrait orientation (smartphones), and it looks bad on tablets.

**Comment by CarlosEsco** [comment]
Welcome to make a fork if you don't like it
