### ISSUE TITLE
[Feature Request] Add multi-window support From Samsung 

### ISSUE THREAD

**Issue by Heavyarms04** [inorichi/tachiyomi#2701]
It would be extremely good to be able to use social networks like Facebook or WhatsApp, browser and players while you read your favorite Mangas 

The application should be able to be seen in Samsung's editable multi-window menu to be added ensuring that easy to use
![Screenshot_2020-03-14-03-15-29-picsay](https://user-images.githubusercontent.com/49253118/76678168-9f9a8500-65a3-11ea-8161-e4e5ac0bbd45.png)
![Screenshot_2020-03-14-03-14-41](https://user-images.githubusercontent.com/49253118/76678171-a4f7cf80-65a3-11ea-881f-2a04e83ea0b6.png)
![Screenshot_2020-03-14-03-13-48](https://user-images.githubusercontent.com/49253118/76678174-aa551a00-65a3-11ea-9cbd-ba98ce7e8ff8.png)

**Comment by AmineI** [comment]
This is *not* Samsung specific so please edit the title I suppose ?

[Relevant docs](https://developer.android.com/guide/topics/ui/multi-window#resizeableActivity)

That already seems to work fine when forcing multi-window support through Android developer options, so it should be fine to enable it for the app by specifying it in the manifest as suggested in the docs.

I tested basic scenarios : resizing during reading or on main views (library/manga info/catalogues/search views.)

Only possible issue I noticed was on the manga info pages, the manga description was out of bounds, with (seemingly) no way to scroll to it

**Comment by arkon** [comment]
> If your app targets API level 24, but you do not specify a value for this attribute, the attribute's value defaults to true.

**Comment by AmineI** [comment]
> > If your app targets API level 24, but you do not specify a value for this attribute, the attribute's value defaults to true.

> If a device runs Android 7.0 or higher, it automatically supports split-screen mode.

Indeed, I assumed not because otherwise the feature wouldn't have been requested.

Then I suppose it does not automatically supports it under 7.0 - which means if @Heavyarms04 does not see the option, it may be because he has Android < 7 and Samsung's own multi-window implementation which came before Android's ? Wouldn't setting the attribute value to true actually help these weird cases ? 

I'll have to research more about that, but it most probably is one of these Samsung quirks, and I was wrong assuming it was due to Android stock implementation (I thought so because Chrome, Youtube and more were supported in the screenshots).

But yeah, I suppose it's not relevant to bloat the Manifest only because of a few devices with improper implementation.
