### ISSUE TITLE
TeamX is not working

### ISSUE THREAD

**Issue by mged** [inorichi/tachiyomi#2750]
Why released new update? i dont get it for real, why would someone release an update that DO NOTHING AT ALL?!

the new update for team x did not fix the issue nor change anything.

i think this is some kind of tradition for the devs here to release useless updates when they get bored?

IDK but please fix teamx issue

**Comment by arkon** [comment]
Idk what your problem is, but multiple people have told you to open it in Webview to let the Cloudflare check to pass first. The update to the **extension** is to increase the page timeout since the site is slow. The **app** updates are entirely unrelated. (Stop posting in the wrong place.)

If you're _still_ having issues, do submit a fix.

**Comment by mged** [comment]
so the issue related to user agent? i can change some codes if its related to that.

**Comment by mged** [comment]
even after i open it in webview and it bypass the cloudflare when i open it again after opening it in webview it still show failed to bypass please do something.
