### ISSUE TITLE
[Bug] Tachiyomi 0.8.5 dont install

### ISSUE THREAD

**Issue by DrkLRd985** [inorichi/tachiyomi#2768]
### Device information
* Tachiyomi version: 0.8.5
* Android version: 5.0

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
The installation conclusion

### Actual behavior
The installation fails with the message:
" X Application not installed"
And below just the option "cancel" 

### Other details
Additional details and attachments.

**Comment by arkon** [comment]
Are you trying to update from an F-Droid installation?

**Comment by RIPASSAS** [comment]
I have the same problem. It happens in fdroid and manually installing the apk

**Comment by arkon** [comment]
The GitHub and F-Droid builds have different signatures. You'll need to install the update from the respective source, or do a backup + uninstall/install the other one if you want to switch.

I believe 0.8.5 is available through F-Droid now too (although we generally don't recommend it since updates are slower).
