### ISSUE TITLE
[Bug] Tachiyomi crashes when updating library

### ISSUE THREAD

**Issue by UsagiKinetik** [inorichi/tachiyomi#2820]
### Device information
* Tachiyomi version: 0.8.4
* Android version: Android 9

## Steps to reproduce
1. Update Library

### Expected behavior
Library updated

### Actual behavior
App closes itself and doesn't finish updating.

### Other details
It seems like the app crashes when it reaches a manga with source from MangaPlus extension.

**Comment by alessandrojean** [comment]
Did you try to update to the latest stable version (v0.8.5) and see if it still happens?

**Comment by kappa7194** [comment]
I had the same problem.

Since a couple of days ago (maybe a week?) some time after starting the library update the app would close on its own and the update progress notification disappear. After manually re-opening the app the update resumes on its own and the cycle repeats.

When the app closes the usual application crash pop-up from Android does not appear.

Updating to version 0.8.5 _seems_ to resolve the issue (it hasn't happened yet).

Using a Samsung Galaxy Tab S4 (SM-T835) with Android 9 updated to Samsung patch 2020-03-01.

**Comment by alessandrojean** [comment]
Probably it's happening some incompatibility between the Kotlin version used in the extension and with the used in v.0.8.4. When I updated Kotlin I tested only with v.0.8.5 in a different range of Android versions and all worked fine, so I would say the way to go is update to v0.8.5 or use the dev.

**Comment by arkon** [comment]
Yup, error logs indicated that a Kotlin String-related function was missing in v0.8.4 since it's using an older version of Kotlin.

Everyone *must* at least update to 0.8.5. 0.8.4. isn't supported anymore.

**Comment by UsagiKinetik** [comment]
I tried installing v 0.8.5 but it won't install even with permissions granted

**Comment by arkon** [comment]
> It would be nice if the app has a way of fetching the update on its own inside the app itself.

It does, but you need to uninstall the f-droid version first to install the github builds.

**Comment by CarlosEsco** [comment]
Fdroid is not officially supported fyi.

**Comment by UsagiKinetik** [comment]
> It does, but you need to uninstall the f-droid version first to install the github builds.
How do you install them? I tried installing them first but they keep failing the installation even when I have the permissions granted?

**Comment by happywillow0** [comment]
0) Ensure you have a good back up if your current library. 
1) Uninstall Fdroid version first.
2) then install GitHub version.
3) restore backup
