### ISSUE TITLE
Error when trying to download a manga 

### ISSUE THREAD

**Issue by FreakyGamer** [inorichi/tachiyomi#2849]
## Device information
* Tachiyomi version: 0.9.83
* Android version: 9.0
* Device: xiaomi redmi note 8 pro

## Steps to reproduce
1. Choose chapter to download 
2. Start the download 

### Expected behavior
The download should start without any problems 

### Actual behavior
I Get the error message after just under a second " Expected URL scheme 'http' or 'https' no colon was found" 

### Other details
In part it is possible to read the manga but only load a few panels. In the web view, the mangas load completely 

![Screenshot_2020-04-09-10-44-19-008_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/18227311/78876138-2cbfe500-7a4f-11ea-9a3b-74a5d9df4a15.jpg)
![Screenshot_2020-04-09-10-44-11-690_eu kanade tachiyomi j2k](https://user-images.githubusercontent.com/18227311/78876139-2d587b80-7a4f-11ea-9afa-b51e9c3f48c6.jpg)

**Comment by arkon** [comment]
What extension?

**Comment by FreakyGamer** [comment]
Seem like mangakakalot is the Problem here

**Comment by SnakeDoc83** [comment]
I've seen this happen with Hatigarm (Genkan) as well.  IIRC correctly the cause was that they had created a chapter on the site without any images.  I can't remember how exactly they messed it up, I just remember looking at the page and there were no images.  I don't think there's anything to do here except perhaps throwing a better error message.

**Comment by Vaturobi** [comment]
I have the same problem can't download from mkakalot/mnelo is this similar to kissm where they ip bnned people using tachi ?
