### ISSUE TITLE
[Feature Request ]

### ISSUE THREAD

**Issue by Crzyadian** [inorichi/tachiyomi#2861]
(Dev user) 

Please bring back 3 dot option in chapter list
Also chapter list like j2k beta 2![J2k md2 beta 2](https://i.imgur.com/QEYqv1y.png)

**Comment by CarlosEsco** [comment]
You didn't even make a argument why it should there

**Comment by Crzyadian** [comment]
@CarlosEsco
The 3 dot feature is more convinient than press and hold for one or two chapter operation

**Comment by CarlosEsco** [comment]
For what features is it faster? Bookmark and  read status is a swipe on the chapter.  Only thing that is long press current is mark previous as read

**Comment by CarlosEsco** [comment]
my bad you are posting a j2k screen and i am thinking we are on the j2k github issues.  So i can be more blunt with my answer.  

Its not coming back.  3 dot chapter, 3 dot top and long press was too many interactions with a chapter and causes confusion.  3 dot on chapter got the ax because it dirties up the view.  You also linked to a j2k beta screen which also does not have the 3 dot menu.
