### ISSUE TITLE
[Feature Request] Backup encryption

### ISSUE THREAD

**Issue by robinknaapen** [inorichi/tachiyomi#2890]
### Why/User Benefit/User Problem
I love the biometrics option, to lock your app is just a really nice addition. Then I found out that backups are just plain json

### What/Requirements
Probably a master key would be a great way to start.

https://developer.android.com/guide/topics/security/cryptography

**Comment by arkon** [comment]
I'm going to reject this on the basis that it'd likely have _very_ little usage, and therefore it wouldn't be worth the effort of adding it, especially when considering the added complexity and support pain of ensuring that people don't accidentally encrypt things then lose their key, then complain because they don't understand what's happening.

If you do need the security, you can always encrypt it yourself before transferring the content elsewhere (assuming your device is already encrypted and secured by some locking mechanism so the issue of it being plaintext is only relevant when people can access it elsewhere).
