### ISSUE TITLE
[Bug] Follow up to Bagdes enhancement #3095

### ISSUE THREAD

**Issue by Matth7878** [inorichi/tachiyomi#3138]
Issue #3095 requesting an option to not display unread badges has been implemented.
Doing so not displaying unread badges as become what is set by default.

But default should be to display them since it was what was done before and what was considered desirable for the user.
Besides right now it changes what was experiencing an existing user when he updates. After update library is not displaying the badges and it feels like there is some kind of bug / regression.

**Comment by Riztard** [comment]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v0.9.2)
- I have updated all extensions
- If this is an issue with an extension, that I should be opening an issue in https://github.com/inorichi/tachiyomi-extensions

**DELETE THIS SECTION IF YOU HAVE READ AND ACKNOWLEDGED IT**

---

### Device information
* Tachiyomi version: ?
* Android version: ?
* Device: ?

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
This should happen.

### Actual behavior
This happened instead.

### Other details
Additional details and attachments.

**Comment by Matth7878** [comment]
Yes I failed to mention I am on latest preview / dev version.
If it's about following template I agree I should have. But it was so minor and I wasn't even sure to report it as a bug.

More importantly : please avoid yelling (caps) and quoting all templates instead of just kindly asking to respect it. I am not sure that's not worse than what I did. 😉

I am off to edit my other issue (which is really a bug). For this one I would rather have the bug label removed.

**Comment by Riztard** [comment]
> More importantly : please avoid yelling (caps) and quoting all templates instead of just kindly asking to respect it. I am not sure that's not worse than what I did. 😉
if its for me, i just copy the text

**Comment by arkon** [comment]
@Riztard Don't spam issues.
