### ISSUE TITLE
[Feature Request] Save/screenshot in Webtoon Format

### ISSUE THREAD

**Issue by hookshot1** [inorichi/tachiyomi#3188]
### Why/User Benefit/User Problem
Saving/screenshoting a normal left/right paged manga saves the source material and chapter/page in the filename, and captures what's on screen.

In webtoon style, it saves the underlying panel, but not necessarily what is seen on screen. This results in fragmented images (when the full image is across panel boundaries) - or screenshoting without all of that source name/chapter/page in the filename.

### What/Requirements
* Save image capability in webtoon views would save the full displayed screen (e.g. combination of panels), rather than the single panel being selected via touch. if it was on the screen when I saved, I want it in the image.
* I'd rather the top and bottom of a panel be included when not seen, than to exclude their whole panel when they were seen
* page number must then become a range for the webtoon format, as multiple pages/panels are likely to be captured
* maybe expose behind a setting if someone wants to opt-in/out of those feature
*

**Comment by arkon** [comment]
There's isn't really a way for us to tell what a panel is without significant effort (i.e. actual image processing), nor do we really have a proper definition of pages in webtoons beyond how the images are actually split up (since there's technically no concept of pages in a long strip format like webtoon anyway...).

It might be something worth considering with a future rearchitecture of the app, but I doubt we'll jump through the hoops of handling webtoons like that.
