### ISSUE TITLE
[Bug] When there is a error with updating it removes the thumbnail and status

### ISSUE THREAD

**Issue by MrAndre96** [inorichi/tachiyomi#3194]
### Device information
* Tachiyomi version: R2331
* Android version: Android 9
* Device: Oneplus 5t

## Steps to reproduce
1. For me it happens most of the time with mangakakalot (since it gives a lot of no chapters found errors) so get a library full of manga from them
2. Update your whole library
3. When you see that you got an error from the notification check on that manga which is stated in the log file
4. You will see that the status and thumbnail both are removed

### Expected behavior
Not removing it when it can't be updated (when there are timeout errors such as this)

### Actual behavior
Removing the status and set it to unknown and removing the thumbnail

### Other details
Easiest to reproduce on mangakakalot but it can happen which every source

**Comment by antocs** [comment]
I updated yesterday after months (i forget to update since no auto-update), I use the dev/preview branch, and this happens to me too.
When you try to update, some manga get "failed to update **x** manga", if you open the log it won't show you the source that errors, only the manga list and the error "no chapters found".
![Image 1](https://user-images.githubusercontent.com/22413659/82642316-feb4ef80-9c0d-11ea-87c8-cd2623d47609.png)
![Image 2](https://user-images.githubusercontent.com/22413659/82642352-0a081b00-9c0e-11ea-8860-f68598b907f1.png)
In these images above it shows the notification for the error, as you can see, the manga that error change.
To fix this (it only works once, you have to do this process every time) I cleared the cache and also updated manga covers (this maybe not required, but I do them together, since I noticed the manga with errors had an entry without cover anymore).

**Comment by MCAxiaz** [comment]
@arkon Pretty sure this is just an extension issue with MangaBox.

Pretty reliably reproducible just by spamming refresh. Some manga details calls will randomly "fail" with this server error
<details>

![](http://puu.sh/FNDja/913ec2f99d.png)

</details>

Looking at the extension code itself explains the rest. The `thumbnail_url` is the only field that doesn't have a check to see if the element is actually in the document, so it ends up being set to an empty string instead of just null; `status` is non-nullable and defaults to 0 (unknown).

**Comment by arkon** [comment]
That seems to correlate with what I've been seeing on my own phone.

I do wonder if there's an actual valid scenario where we'd want to to set `thumbnail_url` to `null` if it's already populated though...
