### ISSUE TITLE
[Feature Request] Option to recheck update in case of "no chapters found" automatically or give an option in the notification

### ISSUE THREAD

**Issue by aakash37** [inorichi/tachiyomi#3226]
### Why/User Benefit/User Problem
The no chapters found just randomly pops up for any manga but it goes away after a recheck.
So if update algorithm could automatically recheck after the library update or give an option in the notification to recheck the failed chapters
Because this happens for 3 to 10 manga so for that rechecking the whole library is a waste as it takes more time and resources

### What/Requirements
Improved library update algorithm to automatically check for update for the failed chapters or give a button in the notification to recheck update for only the failed chapters.

**Comment by arkon** [comment]
It's rather interesting to see the consequences of exposing these errors to users, since the behaviour is exactly the same as before, except users never knew some requests failed.

But anyway, it already does retry a few times before giving up, and I'd rather not have a retry button since users will just abuse it to spam the sources even more in a perpetual feedback loop.
