### ISSUE TITLE
[Feature Request] ability to extract page text

### ISSUE THREAD

**Issue by lmj0011** [inorichi/tachiyomi#3383]
### Why/User Benefit/User Problem

Often when reading manga, you will come across pages that scanlation groups put at the end of a chapter similar to this

<img src="https://user-images.githubusercontent.com/9396189/85642661-bd25c300-b657-11ea-9bec-5618e77ccf24.png" height="500">

It would be nice if you could copy the titles of those 2 mangas and search for them or copy the discord link to view the server.

My current process for doing this, is to screenshot the page and remember to look up the titles or the discord later on(usually I forget). I've tried Google Assist's "What's on my screen" feature, but it doesn't seem to pick up info from the page at all. Having the ability to extract the text so I can highlight it and do a web/manga search would make for easier manga discovery

### What/Requirements

Add a new "long tap" option to the Reader. "Extract text from page"

<img src="https://user-images.githubusercontent.com/9396189/85643542-1bec3c00-b65a-11ea-9086-485c5985ebf0.png" height="500">

When selected, it uses [OCR](https://firebase.google.com/docs/ml-kit/android/recognize-text) to extract the text from the page. (the order of the text is **not expected** to be "in reading order", nor the accuracy to be 100%)

<img src="https://user-images.githubusercontent.com/9396189/85643892-15aa8f80-b65b-11ea-8d4c-a8c04744ee39.png" height="500">

You will now be able to select the text you want. If it's a manga you want to look up, select the title and choose "Add to Search" from the context menu

<img src="https://user-images.githubusercontent.com/9396189/85644202-ecd6ca00-b65b-11ea-8d23-4e85952c2f90.png" height="500">

This queues it up for a global search, you can queue multiple titles

<img src="https://user-images.githubusercontent.com/9396189/85644326-32939280-b65c-11ea-94da-4aed81be4338.png" height="500"> <img src="https://user-images.githubusercontent.com/9396189/85644341-40491800-b65c-11ea-848a-7f6bf44bf376.png" height="500">

Afterwards, select "Search" to perform a global search for the titles selected. (this takes you out of reader mode)

<img src="https://user-images.githubusercontent.com/9396189/85644387-6078d700-b65c-11ea-8918-f56d86f8f75c.png" height="500">

**Comment by lmj0011** [comment]
anyone wanting to test this feature can download this build: https://github.com/lmj0011/tachiyomi/releases/tag/v0.9.2%2Bsha.829743b7

**Comment by serjflint** [comment]
Seems to be too niche. I was reading the same credit page and I think it is faster to type the name manually.

**Comment by vengiare** [comment]
...and I don't think groups would put a link that's lengthy and difficult to type anyway.

**Comment by AmineI** [comment]
Isn't it a bit out of scope for the app?

I get that it's useful, I often need to select text from a page - but in that case I just open Google lens and do it there, I don't think it'd be wise to bloat the app for this

**Comment by AmineI** [comment]
If you're familiar with tools like [Automate](https://play.google.com/store/apps/details?id=com.llamalab.automate) or Tasker, it is easy to create a quick settings tile to invoke Google Lens on any screen.

Google Lens then allows for translation, selection, search, and more, with the on-screen text.

Here's my approach as an [Automate flow](https://llamalab.com/automate/community/flows/35631). There are a few prerequisites though, such as having the Google Lens app installed and set up.

**Comment by lmj0011** [comment]
>I don't think it'd be wise to bloat the app for this.

I doubt a couple of extra MBs is bloating anyone's device using this app, plus the ML model is not part of the app build.


>If you're familiar with tools like Automate or Tasker, it is easy to create a quick settings tile to invoke Google Lens on any screen.

Meh, I like my solution better. The idea of downloading another app just to get the extract text functionality isn't appealing now. Maybe I would have went this route before.

>Google Lens then allows for translation, selection, search, and more, with the on-screen text.

I only ever need selection and search, and I get to go straight to the in-app global search with text I selected. Can Google Lens do that?

**Comment by AmineI** [comment]
> I doubt a couple of extra MBs is bloating anyone's device using this app

I don't mean size-bloat but feature bloat. It has to be maintained, and this being an open-source project, that is also currently being rewrote from the ground up, I hope you'll see why I thought that. Don't get me wrong, I totally get the usefulness of using OCR on a page text though. Anyway, that's ultimately the maintainers decision.

>The idea of downloading another app just to get the extract text functionality isn't appealing now.

On my end it makes sense to use an OCR app to OCR, and a translation app to translate, but I can understand the convenience of having everything in one place :) .

> I only ever need selection and search, and I get to go straight to the in-app global search with text I selected

Indeed, Google Lens can't go straight to the in app global search by itself. But since we're already talking Automate, yep, Automate can do that - because there is a [search intent](https://github.com/inorichi/tachiyomi/pull/1787) for the global search that can be used by any app.

**Comment by arkon** [comment]
So I did see your PR and I think this is cool, but it's ultimately not something I'd want to include in the main app, because:

- App size bloat
- Unsure if the model works for other languages
- Reliance on non-libre Firebase library (blocker for F-Droid, which we implicitly support; technically can use the separate SDK as you mentioned though)
- The usecase doesn't actually seem _that_ common, although you mentioned you apparently do so often?
- Any form of maintenance would probably rely on the author, and it's difficult getting people to actually maintain things over time

Happy to discuss more, but I'd rather be transparent and say that I'm currently not convinced and I didn't want to just let this rot as an open issue and give anyone a false sense of hope.
