### ISSUE TITLE
[Feature Request] Always show bottom navigation

### ISSUE THREAD

**Issue by pervertkirito** [inorichi/tachiyomi#3392]
### User Problem
it irritates me when this happen.

[![video](https://i.imgur.com/CuYEMGf.jpg)](https://streamable.com/9z1hzn)

Bottom navigation won't show up if your library not big enough. Check video ☝️☝️

### Requirements
Add an option for **always show bottom navigation** on settings.
( I actually like the old bottom navigation style :P )

**Comment by lmj0011** [comment]
>Bottom navigation won't show up if your library not big enough.

This seems to only happens when you have the Library display set to show 3 items per row in portrait mode and have exactly 2 rows in a particular category. Changing the "items per row" count to any other number then it works as expected.

**Comment by scb261** [comment]
Tachiyomi version: Stable 0.9.2

Same problem when a category is empty (for example, filtered by unread when all mangas in the category are read). 

~~Also I just don't like when it disappears at all since it takes few seconds for me to recall direction of scroll to made it appear (in the end I just try one way and if it doesn't work, then another one), maybe I just not used to it yet. Not sure how many users share my opinion, but the option _always show bottom navigation_ would be nice.~~ And while writing this comment I understood my problem - **if you scroll up only a little bit, upper bar is shown while the menu isn't and that's what made me confused**. It's better to make them appear together.
