### ISSUE TITLE
[Feature Request] Author search 

### ISSUE THREAD

**Issue by jfcaraujo** [inorichi/tachiyomi#3462]
### Why/User Benefit/User Problem
Most extensions only search by title when using global search (they don't search by description and to search by author they need to use the special author search from that extension's filter) so when clicking on an author name, since that makes a global search with the authors name, most extensions don't show results 

### What/Requirements
When clicking on the author of a manga , instead of making a global search with the name of the author, making a search by author in the same extension (the same as using that extension author search from the filter) 
In case that extension doesn't have author search make a regular search on that extension. (this last part is a suggestion for the exceptions, only the first is actually the requested feature)

**Comment by arkon** [comment]
Global search doesn't search by title per se, it just surfaces whatever the extension's search function will return, which for most sites is usually based on titles. Filters usually involve more complex logic to handle them instead of a regular old search query, so there's no standardized way of doing this with the current API.

Might be worth revisiting for a future revision of the API.

**Comment by arkon** [comment]
https://github.com/tachiyomiorg/android-app/issues/10
