### ISSUE TITLE
[Feature Request] Speech Bubble Zoom

### ISSUE THREAD

**Issue by AdityaAnand99** [inorichi/tachiyomi#3575]
Knew about this app just a few days ago and god it's brilliant but, before this I used to read all my comics on Google play books. There's only one thing that wish tachiyomi had and it's Google's BUBBLE SPEECH ZOOM. It uses machine learning to recognise speech bubbles and intelligently zoom into them for easier reading. Move from bubble to bubble one tap at a time, and still keep the full-page experience. This This vastly improves the reading experience and allows to enjoy the comic without zooming anywhere. The difference is night and day. I got no idea how difficult it'd be port this feature back from Google play books but if you can please do it I'm practically begging you. https://www.theverge.com/platform/amp/2016/7/21/12229074/google-play-books-bubble-zoom-machine-learning-sdcc-2016 
Bubble Zoom on Google Play Books: https://youtu.be/1v7dS8i5G9U

**Comment by arkon** [comment]
I'm not sure if you're the same person that asked for this on Discord the other day, but no because:

- I don't even know where to get that ML model, if it's even available. I also bet it'd fail for manga since it's RTL.
- I doubt anyone would maintain it.
- Improving the experience is subjective, I hate anything that overly modifies the content.
- The Google Play Books thing is still called a "technical preview" despite it coming out 4 years ago?
