### ISSUE TITLE
[Bug] Keyboard not collapsing properly / Search blasting in background

### ISSUE THREAD

**Issue by Rstment25** [inorichi/tachiyomi#3584]
### Device information
* Tachiyomi version: 10.3
* Android version: 8
* Device: Mate 10 Pro

## Steps to reproduce
1. First step

Type anything in search bar

2. Second step

When results show up keyboard still isn't collapsed, you can collapse it if you want but it makes no difference - when you tap on a result it collapses the keyboard, loads description page only to pull up keyboard again. 

Any action after that keeps flashing the keyboard, like going back - it brings you back to the results from the search then again shows the keyboard only to collapse it again. 

Video : https://mega.nz/file/WJ5HlJ5K#I2iVi5wHsji-VoXC2Q8I-oV_wBfmYk6qy0NgzirN9jU

### Expected behavior
This shouldn't happen... Keyboard should collapse as soon as you hit enter to search for results. Then even if the keyboard is open / closed when you tap on a search result it should collapse it if necessary and not flash you with it constantly. 

### Other details
I don't remember seeing this in original 10.0 release, these latest ones introduced the issue as far as I recall. 

### Request

Also, is there a way to remove all the clutter from search results? Like, we don't want to see " No results found ", just show the results instead 👀

And, can we have some latency tracker in the app?

It would help a ton when determining which source is the closest / most responsive. Like what do you do when you're trying to merge? 

Search keeps blasting in the background and you can't even tell if the source you're migrating to is fast / slow. 

### Thats also another issue

Search keeps blasting and slowing down whatever you're doing. You can't just pick one of the results and proceed with reading. No, once you tap on that result the search is still going ... 

Slowing down the whole experience - just to load a single manga page you wait 20+ seconds all because of the search. Dirty solution is find something, wait those 20/30 seconds to loaf a single page then exit to history and load manga from there. 

Really bad experience. Here's the video of what it looks like and how fast it could be if search go fixed ( How fast it loads when I start from history without search getting in the way ) 

https://mega.nz/file/DYInzKbI#nTzXxne39QhhAPibFxD72tsa6lciOB9ilYn37YS0nks

There are few other issues as well but I'll report once I'm sure of how to replicate or why they happen... 

Ty for all the work! I hope we'll see these fixed 😉

**Comment by scb261** [comment]
I also have keyboard flashing issue, but now it's just keyboard icon in corner. Before it was whole keyboard flashing as in the author's video. Just installed 0.9.2 back to check this (~~and it broke my app and erased library, so don't try it~~), the bug is also present (but still it's only keyboard icon and I'm sure that at some point it was whole keyboard)

**Comment by vengiare** [comment]
Make individual issues for each problem. If the issue gets closed, other stuff you mentioned here will rot in hell.

**Comment by arkon** [comment]
So I"m not going to watch the videos since I don't want to download videos from random people, but...

Re: weird keyboard behavior

This is a limitation of the `SearchView` implementation in Android where you can't update the query without it focusing it and triggering the IME. The existing workaround is to quickly clear the focus afterwards, so that's why you're seeing the keyboard flash in and out most of the time. Not a whole lot I can do about that. It appears a bit better on some devices over others.

Re: showing results instead of no results found

How would I do that if there's no results...?

Re: And, can we have some latency tracker in the app?

No. This is a basic manga reading app, not some network tracker tool.

Re: Search lag

Please open a separate issue. I think one other person has mentioned lag from global searching before, but nobody else has.

**Comment by Rstment25** [comment]
Ty for the explanation on keyboard issue. 

How would I do that if there's no results...?

Just don't show the message itself, imagine 100 sources and only 1 has the search results. How are you gonna find that in the sea of "No results Found" messages? Very hard...

Rest I don't feel like commenting on, that's the basics of any commercial manga reader out there but it seems like I'm speaking in deaf ears. You are jumping on prejudice without even considering why the stuff I mentioned matters. 

Background network analysis is bread and butter of how online connectivity works. I don't see why this app shouldn't do the same, especially when you're dealing with tons of different sources scattered all over the world using god knows where located servers. What would be the background job of commercial manga readers, routing your traffic the optimal route could be a great addition in the way of latency / bandwidth trackers that the users can use to perform the same job themselves.

Even if you're not accepting of constructive criticism I still thank you for keeping up with the development. 

Take care!
