### ISSUE TITLE
[Feature Request]: separately activating Page transition animation for "webtoons"

### ISSUE THREAD

**Issue by mrh1377** [inorichi/tachiyomi#3594]
### User Problem
In the past when page transition was disabled it was still active in webtoon reading mode however now when page transition is deactivated we have instantaneous transmissions in webtoon reading mode which is off-putting when reading a long strip content.

### Requirements
I request a separate toggle in the settings for activating and deactivating page transitions for webtoons.

**Comment by CarlosEsco** [comment]
related commit
https://github.com/inorichi/tachiyomi/commit/b363b9fc1a5f3cd574bf0829d90b50319b83aeee#diff-d63df2ae1ff60a2f7c22ef5098f5ef42

@arkon  i've attached videos mrh provided on discord.  After seeing them.  I dont know why you would ever want smooth scroll disabled on webtoon
Disabled
![disabled](https://user-images.githubusercontent.com/2092019/89298174-f11add80-d632-11ea-9b2a-5823454cc8bc.gif)

Enabled
![enabled](https://user-images.githubusercontent.com/2092019/89298404-4bb43980-d633-11ea-9e25-352375065813.gif)

**Comment by arkon** [comment]
To be fair, I have no reason to ever disable them. However, I can see it being something useful for those with vision impairments or low refresh rate devices.

**Comment by arkon** [comment]
A future app update will make toggling settings from the reader easier, so that'll be the compromise here 

I don't intend on reverting or duplicating the setting as we'd ideally hide the fact that the reading modes have 2 underlying implementations hidden from end users.

**Comment by mrh1377** [comment]
> related commit
> [b363b9f#diff-d63df2ae1ff60a2f7c22ef5098f5ef42](https://github.com/inorichi/tachiyomi/commit/b363b9fc1a5f3cd574bf0829d90b50319b83aeee#diff-d63df2ae1ff60a2f7c22ef5098f5ef42)
> 
> @arkon i've attached videos mrh provided on discord. After seeing them. I dont know why you would ever want smooth scroll disabled on webtoon
> Disabled
> ![disabled](https://user-images.githubusercontent.com/2092019/89298174-f11add80-d632-11ea-9b2a-5823454cc8bc.gif)
> 
> Enabled
> ![enabled](https://user-images.githubusercontent.com/2092019/89298404-4bb43980-d633-11ea-9e25-352375065813.gif)

I don't want to disable it on webtoons thats my problem because in the previous update it never could have been disabled. I just want to disable it for manga however now when I disable it it also disables it for webtoons as well so when i switch between reading manga or reading webtoons I have to go and disable and enable this over and over.

**Comment by scb261** [comment]
I was thinking about it, doesn't app already has 2 separate settings for cropping borders? Can be the same for page transition. I prefer read manga without the animation. I don't think that the cropping option should be fused just because now it 'hides' second implementation, same for the page transition.
![IMG_20200805_175345](https://user-images.githubusercontent.com/65343233/89429263-0a607e80-d746-11ea-92d3-2b64d9b10e34.png)

**Comment by CarlosEsco** [comment]
the crop was unmerged because its not always consistent and will be readdressed later

**Comment by scb261** [comment]
So with some time it will be merged? Given that it'll work right for webtoons. If so, I can understand merging cropping.

But I still don't see why the transition cannot be unmerged. In webtoon it helps to see where you finished before transition, while in pager it just takes time to change page and 'blinks' (not sure what term to use here since English is my second language) in user's eyes.
