### ISSUE TITLE
[Feature Request] Add an option to revert to old download icon color

### ISSUE THREAD

**Issue by einstein95** [inorichi/tachiyomi#3610]
### Why/User Benefit/User Problem
Because some people do not like green download icons, or have gotten used to them being red.

### What/Requirements
Just put it in an option tucked out of sight, it doesn't need to be so hard. The previous issue was closed with 2e9d89574d97c2c702d7c318494f2ec4cebf9c4d but that does nothing to alleviate the problem.

**Comment by Soitora** [comment]
The "why" reason is not really good enough to justify adding the option for it.

Being used to a color or preferring a color is no real reason for us to add and maintaining an option like this.

**Comment by CarlosEsco** [comment]
Not happening

**Comment by einstein95** [comment]
Maybe, _just maybe_, the change shouldn't have been forced on users in the first place? If people want to use J2K, they'd use J2K.

**Comment by joseph619** [comment]
Users are free to fork the app if they dislike any change, this an open source project after all (just as J2K fork owner did)

**Comment by einstein95** [comment]
Users shouldn't have to fork an app over a change they dislike that was forced upon them with any criticism being met with "lol wontfix"

**Comment by Soitora** [comment]
The reasoning wasn't "lol won't fix".
The change wasn't due to Jay's fork.

**Comment by Ecconia** [comment]
There is one valid reason why such an option would be helpful.

When using a (these days very common) blue-light-filter the green indicator looks like a blue indicator. Given its not next to the actual blue indicator.

It just makes it (at least for my eyes) impossible to distinguish from blue. Thus I have to turn off the blue-light-filter (outch) to actually see the difference or use my memory to know which I downloaded (its a bad memory).

Either way its annoying. Thus an option would help a lot. But since it already has been rejected, I will just make sad noises and look for some fixing fork.

Its sad to see at which points UI design fails.

**Comment by vengiare** [comment]
well that's another feature request, this is already closed and is unrelated to yours which is for adjusting contrast
