### ISSUE TITLE
[Enhancement] Use gzip request while scraping - for all sources

### ISSUE THREAD

**Issue by Akianonymus** [inorichi/tachiyomi#3628]
This will greatly improve the speed when scraping. html scraping or api requests, gzip header shouldn't have a problem.

Reference: https://github.com/inorichi/tachiyomi/commit/40a959501234179da726f42805a869dae3cc0a0a

Note: This issue was originally created in tachiyomi-extensions repo but moved here on request by  @SnakeDoc83 ( [old issue](https://github.com/inorichi/tachiyomi-extensions/issues/4022) ).

**Comment by SnakeDoc83** [comment]
My understanding is that OkHttp requests gzip by default and silently decompresses; so this may be pointless. If I'm wrong or there's something to be gained by explicitly sending the header and manually decompressing, it seems to me it would make more sense to make the change at the app-level rather than modding every extension.

**Comment by Akianonymus** [comment]
@SnakeDoc83 Oops, i didn't know Okhttp did that.

Well, sending an additional header won't do anything, this can be closed i guess.
