### ISSUE TITLE
HTTP Error 404

### ISSUE THREAD

**Issue by Hirigaya** [inorichi/tachiyomi#3768]
When reading an undownloaded chapter it always say HTTP Error 404 that is pretty weird

**Comment by scb261** [comment]
Most probably this issue will be closed by maintainers of the repo because of lack of information and because it's your or source issue, not tachi's issue. Try [troubleshooting](https://tachiyomi.org/help/guides/troubleshooting-problems/#troubleshooting-problems), and if it won't help, go to [discord server](https://discord.com/invite/tachiyomi) and use #support channel.
