### ISSUE TITLE
[Bug] <error http error 429>

### ISSUE THREAD

**Issue by Zextokar** [inorichi/tachiyomi#3794]
## Device information
* Tachiyomi version: 0.10.4
* Android version: 7.0
* Device: alcatel

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
This should happen.

### Actual behavior
This happened instead.

## Other details
tengo unos errores que dicen http error 403 y 429

**Comment by scb261** [comment]
Stop opening issues about it. TuMangaOnline is blocking you because of big amount of requests from you. You can either:

- Wait for some time. While you're waiting, separate your library into categories and update each category separately with some time between updates.
- Migrate some manga to another source.

**Comment by Zextokar** [comment]
y que hago si me banearon la ip de lectortmo

**Comment by scb261** [comment]
https://tachiyomi.org/help/guides/source-migration/#source-migration
