### ISSUE TITLE
[Feature Request]  Reddit like Thumbnail blurring.>

### ISSUE THREAD

**Issue by monMusu** [inorichi/tachiyomi#3797]
**So**, I was checking out Tachiyomi release candidate v2688 and came across the Parental Control function, which though an interesting option is severely crippled,that is, it blocks extensions and sources. While leaving out all the NSFW Manga covers out in the open. I dont see the point here.
   **Now**, to make it more potent, we could have a NSFW filter like Reddit that blurs image thumbnails or Myfigurecollection, that replaces thumbnails with a dummy.
The way this should work is, you have a check box in Parental Settings or a new setting,  clicking on which, all Manga's tagged NSFW should have their covers blurred  or blocked.

This IMO, is a better method than SY's, of simply hiding covers. 

▶  **Tachiyomi**

![ScreenMaster_20200914_112131.png](https://user-images.githubusercontent.com/70755549/93083839-d1a2b600-f6b0-11ea-93ac-692d58925fa4.png)

▶  **Myfigurecollection**

![ScreenMaster_20200914_162906.png](https://user-images.githubusercontent.com/70755549/93083856-d8c9c400-f6b0-11ea-851b-77b36cb77700.png)

**Comment by arkon** [comment]
The parental controls is pretty half baked right now and that's why it hasn't made it out to any of the stable releases yet.

That being said, it's currently just meant to avoid allowing browsing the sources. The concept of parental controls doesn't quite make sense if the library you're handing off to a child already has NSFW content in it for some reason.
