### ISSUE TITLE
Feature : Myanimelist sync last chapter read

### ISSUE THREAD

**Issue by jscti** [inorichi/tachiyomi#383]
Hi there

MAL sync auto update MAL progress when finished reading a chapter. That's perfect.
Now, imagine you have 2 devices with the same manga DB (through backup/restore), it would be great to have an option to automatically (or on demand) update the last read chapter on tachiyomi based on the value of MAL progress for this manga.. That way tachiyomi would have a built-in cross-device functionnality !

- if "MAL progress" > "Tachiyomi progress" => update Tachiyomi progress with MAL value.

BTW, thanks for this great app, I'll take a look at Kotlin that I didn't know, maybe i'll be able to help on this project ;)

**Comment by j2ghz** [comment]
I wanted to suggest the same. Here's my idea:
There'd be a setting (default off). When it's on and you open manga, it starts getting last chapter number from MAL. Once you tap the blue FAB, if not finished, it shows progress, if finished, shows the chapter. If it wasn't able to recognize that chapter, it shows a dialog that tells you the chapter number so you can select it on your own. Once a chapter is opened that way, all the previous ones are marked as read. Also a setting, that enables you to always review which chapter it wants to open, instead of only chowing the dialog if it wasn't able to choose.

I also though for even better recognition you could put last chapter name inside `<comments></comments>` http://myanimelist.net/modules.php?go=api#mangavalues

**Comment by inorichi** [comment]
I think it would be easier, better and more efficient to sync with a spreadsheet on GDrive than using MAL.

**Comment by VirusEcks** [comment]
simple database file - may be sqlite- and sync to drive or dropbox as normal

but maybe you should consider that at one point you might add the source switching (or sources merging) so that the progress/bookmark sync for every manga with same name will be synced across all available sources

so the db structure should be based on manga name not source

**Comment by j2ghz** [comment]
@inorichi It is for Tachiyomi to Tachiyomi sync

**Comment by inorichi** [comment]
I won't use MAL for syncing devices. If syncing is implemented, it would be file based in some cloud service.
