### ISSUE TITLE
[Feature Request] Move Downloaded Only under Downloads

### ISSUE THREAD

**Issue by loocool2** [inorichi/tachiyomi#3837]
## Why/User Benefit/User Problem
Too many users are turning on the feature without realizing, or knowing what it does. It's too easy to turn it on.
![image](https://user-images.githubusercontent.com/36128021/93988225-50e15b00-fd3d-11ea-958f-ac66a052f599.png)
## What/Requirements
The switch would be under the downloaded section instead. A better description of what the feature does would also help.

**Comment by CarlosEsco** [comment]
The whole point of it though seems to be a quick switch to offline reading only.

**Comment by scb261** [comment]
Maybe move it to library screen then. But I'm not sure where to exactly:
- Under filter. The filter is about displaying manga in library and not about offline mode. But many users sends screenshots from filter where download checkmark is grayed out, so maybe it's actually the place for it.
- Add one more option to top right. It's already has three buttons, so it would mean adding three-dot menu and hiding some already existing options under it, just like SY did to add two more options there. And I don't like how it hides update library under it. Also users still could change the option there and forget about it.

Another option is to change or add some text:
- Change this to "More > Downloaded only is enabled"
![Screenshot_2020-09-23-14-42-09](https://user-images.githubusercontent.com/65343233/94008456-b9ffb780-fdab-11ea-83c9-308d521a759f.png)
- Add "'Downloaded only' mode is enabled. You cane disable it in More" here. Maybe even add button that would redirect to More, since the sheet hides bottom bar.
![Screenshot_2020-09-23-14-42-19](https://user-images.githubusercontent.com/65343233/94008463-be2bd500-fdab-11ea-97be-a857706f5a39.png)

**Comment by arkon** [comment]
I changed it so that the banner shows up everywhere, so it appears right when you toggle in More. That _should_ make it more obvious to the user what's happening and ideally they'd remember it.

We can reopen/revisit this if people are still confused after the next release.
