### ISSUE TITLE
Not marked as downloaded

### ISSUE THREAD

**Issue by Johndeep** [inorichi/tachiyomi#385]
If I'm beginning an arbitrary chapter of an arbitrary manga, the chapter is **not** marked as downloaded and therefore **cannot** be filtered by "Downloaded", although the images are downloaded and stored in the directory (aka, it uses space on phone). Only if I intentionally download that chapter, it'll be marked as "Downloaded" **and** it can be filtered by "Downloaded".

Also, if I reach the beginning or end of a chapter and then jump to the corresponding next or previous chapter, that and following chapters also won't be marked as downloaded.

It would be nice (although I'm not sure how much work this would need), if downloaded chapter (regardless how it were downloaded) is actually **marked** as downloaded.

This problem should be independent from type of device, I think. And hopefully this isn't a redundant issue.

Version: v0.2.2.1 from f-Droid (Android 5.1)

**Comment by inorichi** [comment]
Even if the images are stored in the filesystem it doesn't mean the chapter can be marked as downloaded. Online reading uses an LRU cache with a maximum size and the files can be evicted at any moment, so keeping track of them doesn't make sense. Also they are unorganized, unlike downloaded chapters.

There could be a setting to use the downloader instead of the LRU cache when opening a chapter, but for now it won't be implemented.
