### ISSUE TITLE
Delete ALL Downloaded and Read chapters

### ISSUE THREAD

**Issue by IamHeinous** [inorichi/tachiyomi#390]
Version: r2. 2-1

Please add an option to delete all read and downloaded chapter in a selected Manga. The delete after reading does Not work for some reason. 

If possible add an option to  auto delete the penultimate chapter. 

Also please add "read" in the sorting. Currently "unread" and "downloaded" is not enough. 

Thanks and more great things may come your WY.

**Comment by NoodleMage** [comment]
What is your Android version. Because delete after read works fine on the devices I used for testing (did you activate in settings?

With penultimate do you mean last but on after reading or delete all but the last one?

With sort I think you mean filter? And if this is the case why should you want read only?

Thanks for the feedback

**Comment by IamHeinous** [comment]
Using 5.0.   yes, it is activated, didn't realize there were two extra subsetting needed to be on. 

2nd to the last chapter. Sometimes I like to back read. So saving the last 2 read chapters I best. 

Yes it is the filters, it's a way for me to see what I have read and possibly delete them.
