### ISSUE TITLE
Reverse tap zones for changing pages when reading

### ISSUE THREAD

**Issue by psychowood** [inorichi/tachiyomi#396]
Hi,
I was wondering if it could be useful to add an additional option that reverses the "tap zones" when reading, relatively to the viewer type.

For example: I'm reading a manga, with the right-to-left viewer (this way double-sided pages start correctly from the right side), but since I'm right-handed I'd like to keep touching the right side of the screen to advance to the next one.

I'll probably try to implement that myself anyway, I'm checking the terrain before issuing a pull request :)

**Comment by inorichi** [comment]
Configurable tap zones may be a nice addition, but I'm not sure how that should be implemented (and probably a configuration per viewer...).

 I like how Moon reader allows that customization, the default tap zones have an "L" form, instead of just three columns (left, center, right). We could change tap zones to that configuration.

If you want a fast fix, take a look at the `PagerReader` implementation, there should be a gesture detector around there. Keep in mind the right-to-left reader is inverted 180º and the images another 180º because this was the easiest option to support that kind of reader, so you will have X and Y coordinates inverted.

**Comment by arkon** [comment]
Added in #3360
