### ISSUE TITLE
[Feature Request] Add more badges types

### ISSUE THREAD

**Issue by Playermet** [inorichi/tachiyomi#4089]
## Why/User Benefit/User Problem
Allows differentiating between ongoing/completed/dropped titles (especially ones without unread chapters).
Really helps to sort and clean up the user's library.

## What/Requirements
Use golden background color for badges for titles determined as completed.
Display golden checkmark if all chapters are read.

Use gray background color for badges for titles that are not completed and not updated for a year (or time period defined in the settings).
Display a gray circle if all chapters are read.

**Comment by joseph619** [comment]
This isn't really reliable since completed status depends on manga websites labelling properly, which is often not the case. And some sources like Mangadex define completed differently than other sites. 

You should use Categories to clean up library, based on Completed, Ongoing and Dropped. Badges won't help with those.

**Comment by Playermet** [comment]
I am already using Categories for actual Categories.
> Badges won't help with those.
They will speed up the process of checking discontinued titles.

**Comment by arkon** [comment]
The completed (and not completed) filter gets you most of the way there. Dropped isn't quite handled nicely in that (i.e. it's just lumped under not completed), but those should be relatively rare.
