### ISSUE TITLE
[Feature Request] Improvements to time, battery and chapter view

### ISSUE THREAD

**Issue by joaoandre120** [inorichi/tachiyomi#4094]
## Why/User Benefit/User Problem
Hi guys,

- [ ] 1. I usually read in my lunch time, so I have to always be aware of the time. If there was an option to show or not (for those that don't want to) the time, battery status and the chapter we are reading (not necessarily needed, but would be good too), on top of screen when reading in full screen mode.
So we wouldn't have to swap down the screen to see  the "android status bar" (I don't know the right name).

- [ ] 2. Sometimes we want to see which chapter we stopped the reading, it would be good to see it on the floating button, so we wouldn't have to scroll down to know it.

- [ ] 3. The possibility to choose the location of the "long press save image".

- [ ] 4. When we long press an page show a border delimiter for it. So we can see which we pressed.

## What/Requirements
1. A translucent gray background would be placed at the top right of the screen with the information in white text. This way it would not disturb the reading / visualization of the image behind, and it would be easy to read the time and battery. And in order not to be updated every second or minute, or in a new routine or thread, it could be updated only when loading a new page. 

2. Show last opened/read chapter on "floating resume/start button". It could be placed right next to the "play icon".

3. On "Settings -> Reader" add the possibility to choose the location to save the image, like on "Download location".

PS. Sorry for any mistake. and thanks.

## Examples: 
(Sorry for the lack of quality, I'm not a designer)
1.
![Screenshot_20201206-110523_Tachiyomi](https://user-images.githubusercontent.com/7441934/101285129-55f16a80-37c2-11eb-8a27-1e554301824c.jpg)
Just a suggestion about the battery icons (found on Google, if there is a standard on android, it could also be used):
![nível-da-carga-do-ícone-da-bateria-30508835](https://user-images.githubusercontent.com/7441934/101285455-ff852b80-37c3-11eb-90a0-ba5a41f1b4c9.jpg)

2.
![Screenshot_20201206-110535_Tachiyomi](https://user-images.githubusercontent.com/7441934/101285689-4aec0980-37c5-11eb-97fc-13342974eff2.jpg)
![Screenshot_20201206-110554_Tachiyomi](https://user-images.githubusercontent.com/7441934/101285691-4cb5cd00-37c5-11eb-9aa7-96b2fd456769.jpg)

4.
![Screenshot_20201206-133133_Tachiyomi](https://user-images.githubusercontent.com/7441934/101286388-02cee600-37c9-11eb-9b6a-7d926ba2662d.jpg)

**Comment by arkon** [comment]
You should create 1 issue per request in the future.

---

1. You should just turn off fullscreen if you need to see the status bar's contents. I realize it also shows the on-screen nav bar too, but re-implementing a status bar to hit a niche use case isn't very resource efficient.

2. The J2K fork shows this as a button with that info but we decided not to do that in the main app as the FAB is more accessible while scrolling. Adding more content doesn't seem great either.

3. I thought there was an existing open issue for this, but I can't find it right now. Please create a separate issue with just this feature request if there isn't already one.

4. Judging from your screenshot, I guess this is for the webtoons usecase because you can't tell what different pages are? I'm not sure if borders will be super useful depending on how the sources decide to cut them up, but ultimately you should be able to tell what the page was after doing the action, right?

**Comment by joaoandre120** [comment]
> You should create 1 issue per request in the future.

   Sorry, next time I'll open one for each.

1. It would not be exactly a re-implementation of the status bar, but at least show the time in full screen mode.

2. It would make to be able to see the last chapter read, without scrolling.

3. I'll re-look for it, if I don't find, I'll open one for it later.

4. Yes, it's a webtoon, sometimes it's cut into several pieces, dividing the drawing, which we would like to save.

And thank you for the answer.

**Comment by arkon** [comment]
1. I'm going to reject this on the basis that the OS already provides this to you.

2. Also rejecting this, mostly because I don't like the idea. As a workaround, you can use the filters/sorts to make it so the first unread is at the top of the list.

3. Please open a new issue if it doesn't exist.

4. Also going to reject this since you can see it after doing the action, sorry.
