### ISSUE TITLE
One finger zoom

### ISSUE THREAD

**Issue by j2ghz** [inorichi/tachiyomi#41]
The whole app is usable with one hand, so it's really annoying to have to pinch zoom. I propose zoom like mangawatcher has: you long press, and then zoom by moving finger up or down

**Comment by wopian** [comment]
Also the ability to move around the zoomed in page with 1 finger, having to keep 2 fingers pinched on the screen to move around is really awkward for manga with lots of (small) text.

**Comment by inorichi** [comment]
@wopian That only happens with the vertical/webtoon viewer. I had to do [this](https://github.com/inorichi/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/vertical/VerticalPager.java#L134) in the vertical one because sometimes it didn't change pages (probably the reason you have to move with 2 fingers). I'm using [VerticalViewPager](https://github.com/castorflex/VerticalViewPager), which I merged with the latest version of the support library [here](https://github.com/inorichi/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/vertical/VerticalViewPagerImpl.java). It happens on both versions, and I don't have any clue of the main cause.

**Comment by inorichi** [comment]
Fixed events on vertical readers.

Isn't double tap enough? It's also a one finger solution.

**Comment by j2ghz** [comment]
> It is, but now the zoom on double tap is too strong.

is what I wanted to write but then I checked and the zoom is ok.

The only problem for me were double pages and that is now solved.

**Comment by inorichi** [comment]
Closing then. :)

**Comment by iBaer** [comment]
@inorichi Not sure if you used Manga Watcher once before (not sure if other readers also have/had the same method).
the one finger zoom (hold and pull up/down to zoom in/out) is the most comfortable zoom and precise method there is for one finger. the double tap is okayish, but it's not really precise as it is.
