### ISSUE TITLE
[Feature] Hide chapters

### ISSUE THREAD

**Issue by YautjaTNT** [inorichi/tachiyomi#442]
Perhaps an option to hide chapters of a manga? I've noticed that practically all catalogues, especially batoto, have several manga with several duplicate chapters, and it think it'd be nice to have a little way to just hide those. Kind of like the hidden files you can have on windows.

**Comment by wopian** [comment]
Mark the duplicate chapters by another scanlator as read using the 3-dot menu? That's what I've been doing for duplicate chapters.

Auto-hiding duplicates would cause an issue where you might be given a quick/shit/troll translation instead of the proper release (I.e does it pick the first or last of the duplicates)

**Comment by inorichi** [comment]
Sorry but I won't add a hidden state. It just introduces more maintenance and more bugs. At most, I would add a way to ignore read chapters within the reader, so you mark duplicates as read and that's it.
