### ISSUE TITLE
Automatically add manga to library when downloaded

### ISSUE THREAD

**Issue by Kamui-Solo** [inorichi/tachiyomi#448]
I see nobody answer me in another issue. I will ask again:

> Then maybe it would be good if we will automatically add to bookmarks manga which we downloaded? Very often I download some chapters for reading later, but forgetting to add this manga to bookmarks, and then I need find this manga in catalogue again for reading, but if there's no internet connection I can't do that.

**Comment by ThePreviousOne** [comment]
That or show `Downloaded` as a tab in the downloads fragment.
But yes "I at least" think your Idea for auto-adding is good

**Comment by NoodleMage** [comment]
I don't think this feature should be added. The natural behavior of the app is that manga's get added when you "bookmark" them. Suddenly adding them when you download one or more chapters would confuse me personally. Also you have the "Last read" chapter view to see which manga's you have read and aren't in your library. 

As for Downloads Tab see #412

**Comment by ThePreviousOne** [comment]
@NoodleMage I agree with you, and i'm not sure why he's downloading chapter before adding the manga to his library.
but the point is that If you download something not in your library its basically gone ( untill you can access the catalogue again Thats why I purpose I a downloaded tab or filter for the Queue

**Comment by inorichi** [comment]
How about disabling downloads from the catalogue? Telling the user to add it to the library first.

**Comment by ThePreviousOne** [comment]
@inorichi disabling probably best (at least in the release builds, if that's not a lot of work). My theory is If one person is 'telling us' they do it there are others, or at least there will be others, who won't. We can't tell those people anything

**Comment by IamHeinous** [comment]
I personally like reading the 1st chapter of an unbookmarked Manga under catalogs to see if the Manga is good or not. If it is good then it gets a bookmark, if bad then I don't bookmark it. I like the idea that pressing the download of an unbookmarked Manga would cause a prompt to bookmark it. As long it does not cause issues with viewing it live without downloading. Just going straight to any chapter then auto downloading the pictures.

**Comment by null-dev** [comment]
Maybe instead of denying the download we could warn the user about it
instead?

I would also like to propose an option or pop-up for automatically deleting
downloaded chapters when the user removes a Manga from their library.

**Comment by NoodleMage** [comment]
A dialog pop-up sounds good to me. Will probably look into this after I finish color filter ;).

**Comment by Kamui-Solo** [comment]
About automatically adding to bookmarks, it's not must be hard-coded, there can be option in settings. But I think about notification, that could be good idea, need to try.

**Comment by corneadoug** [comment]
I had the same issue when starting using the app, I downloaded different Mangas, but only bookmarked the ongoing one thinking it would be mainly to get updates. In the end the real issue is that after it has been downloaded without bookmark, there is no way to access it directly, nor to delete it.

And to show how related bookmark and downloaded content are, when deleting something from the library it does not remove the downloaded chapters.

To me this is not really about having an easy access to content you downloaded, but more of an easy way to delete the content you downloaded (which takes space)

Considering previous discussions, only 2 ways would solve this:
- Do not allow download if not bookmarked, and delete content if un-bookmarked
- Auto-bookmark when chapters are downloaded, delete content if un-bookmarked
