### ISSUE TITLE
Non-dev updates on F-Droid

### ISSUE THREAD

**Issue by carks32** [inorichi/tachiyomi#507]
I know it might be a problem on F-Droid's end but gotta ask. Did you push out the newest update on the non-dev repo for F-Droid? Again, sorry if you already did and you're just waiting for F-Droid to put it public.

**Comment by ThePreviousOne** [comment]
thats not how F-Droid works (AFAIK)

**Comment by inorichi** [comment]
I can't publish my releases there. They do everything.

They detected a new release, but the problem is that they have to accept Google's licenses, see the last lines in https://f-droid.org/wiki/page/eu.kanade.tachiyomi/lastbuild_12

I'll probably release 0.3.2 this weekend, and hopefully they have already fixed that.

**Comment by j2ghz** [comment]
https://gitlab.com/fdroid/fdroiddata/issues/534

**Comment by carks32** [comment]
Ahh, makes sene. Sorry!
