### ISSUE TITLE
Some titles contain html escaped sequences in them

### ISSUE THREAD

**Issue by nurupo** [inorichi/tachiyomi#571]
Version: v0.4.0

Tachiyomi displays the apostrophe in [JOJO'S BIZARRE ADVENTURE PART 5: VENTO AUREO](http://www.mangahere.co/manga/jojo_s_bizarre_adventure_part_5_vento_aureo/) (Mangahere (EN)) as `&#039;`. The full title it displays is `JoJo&#039;s Bizzare Adve ... to Aureo`. It displays this html escape sequence only in My library, in chapters names in Library updates and in the top bar when you select the manga from the My library. The chapter names in the selected from My library manga don't show the escape sequence, they display the apostrophe correctly.

If you open Latest updates for Mangahere (EN), you can find several more cases of this, e.g. [YUMI'S CELLS](http://www.mangahere.co/manga/yumi_s_cells/) and [NAN&BEI](http://www.mangahere.co/manga/nan_bei/) are displayed as `Yumi&#039;s Cells` and `NAN&amp;BEI`.

As a counter-example, [JOJO'S BIZARRE ADVENTURE PART 6: STONE OCEAN](http://www.mangahere.co/manga/jojo_s_bizarre_adventure_part_6_stone_ocean/) seems to be displayed correctly everywhere, I don't see it using the the html escape sequence anywhere.

**Comment by jshap70** [comment]
Hmm, strangely my first theory was incorrect, which was that maybe on the site itself one was stored as a quote character and one was using the html character, but the raw html sources have 
```html
JOJO&#039;S BIZARRE ADVENTURE PART 6: STONE OCEAN
```
and 
```html
JOJO&#039;S BIZARRE ADVENTURE PART 5: VENTO AUREO
```
set as their titles.

**Comment by reconman** [comment]
This is the site used in Mangahere.kt for getting manga titles: http://www.mangahere.co/directory/?views.za

As you can see the HTML escape characters are present. By using the title instead of the text the correct titles can be shown. The only problem is that Tachiyomi will use cached titles as long as the local database is not emptied.

Is the database emptied on every update? If yes then I could check in the bug fix and users would see the correct titles. If not is there any way?

**Comment by reconman** [comment]
@inorchi About the titles stored in the database, are they refreshed on every version update? I've described a problem in a comment above.

**Comment by inorichi** [comment]
No, they aren't. You have to use the clear database setting (after unbookmarking every manga with the issue).
