### ISSUE TITLE
Add a "change orientation" button

### ISSUE THREAD

**Issue by ywecur** [inorichi/tachiyomi#573]
If you have screen orientation locked (common for many people) and a wide page appears, you have to manually unlock it, then flip the phone. Then on the next page flip the phone again and lock it again. 

Including a button, similar to how YouTube does it, that toggles between portrait and landscape would be a lot faster and an overall better experience.

**Comment by blackgin** [comment]
I was looking into the code trying to understand how this can be implemented and I think there are two options here, when the users taps on the button to switch the orientation:

1. The preference `pref_rotation_type_key` is set to 3 (lock portrait) or 4 (lock landscape) depending on the current orientation of the activity.
2. The orientation is forced only on the current activity instance. In this case, we have to track that the user  pressed the button so that we don't resubscribe to the observable of the preference mentioned above.

What do you guys think?

**Comment by arkon** [comment]
This is technically built into Android P+.

**Comment by arkon** [comment]
I feel like this should really just be handled outside of the app, so going to close this.
