### ISSUE TITLE
Problems with 1-page chapters

### ISSUE THREAD

**Issue by coolkid3245** [inorichi/tachiyomi#620]
I'm currently reading [Tomo-chan wa Onnanoko!](http://www.mangahere.co/manga/tomo_chan_wa_onnanoko/) from mangahere (although other sources also only have 1 page per chapter)
The issue is, after 3-5 chapters, when I go forward it shows the previous chapter, but the UI shows the "correct" chapter (ex: page is 211, Tachiyomi UI shows 222 etc) if I continue, it loops the last chapters even though the UI chapters go forward. (ex: page 211, UI shows 230)

Version:  v0.4.1 newest f-droid
Redmi Note 4 MIUI8 Android 6.0, root + xposed

**Comment by inorichi** [comment]
The problem is you are going to the next chapter before it can be appended (slow network or server), and this forces the reader to set that chapter as the active one (removing the previous chapters from the screen).

I can't find a fix in the code for this case, however there are two workarounds. It won't happen if you download the chapters. Another option is to swipe the pages, instead of tapping. Swipe the page a bit, if you don't see the beginning of the next page, wait 1 or 2 seconds and try again.

I'll keep this open but don't expect too much, it may require a rewrite of the reader, so I'd recommend you to use one of the workarounds.

**Comment by inorichi** [comment]
It was easier than I thought. This bug was introduced in c0a0d60 and it happens when the page number doesn't change.
