### ISSUE TITLE
Issue with reading downloaded comics

### ISSUE THREAD

**Issue by ZorbaWas** [inorichi/tachiyomi#640]
Version: r1063 and v0.4.2
Android 4.4.2 and 4.4.4

Tested both in my phone (4.4.2 with v0.4.2 ) and tablet (andorid 4.4.4 with r1063 and v0.4.2)

Having trouble with reading downloaded comics (haven't found a manga that dosen't work). 
Comics download from ReadComic.tv with YAML file found on wiki.

Downloaded Comics:
"Image" - Can't load the image 
"Skia" - Can't load the image 
"Rapid"  - Loads image in black/white or has show:
![screenshot_2017-01-18-16-09-40](https://cloud.githubusercontent.com/assets/16392037/22074133/4208e056-dd9f-11e6-8e8e-86f927012b66.png)
 (when like this, it is always colored below the same line, notice some weird colored lines)

Not Downloaded:
"Image" - Perfectly!
![screenshot_2017-01-18-16-07-45](https://cloud.githubusercontent.com/assets/16392037/22074311/dbdcd2e6-dd9f-11e6-919f-dcaafa7c8615.png)
"Skia" - Black and white image
"Rapid"  - Exactly the same way showed when donwloaded

Don't know if is a problem with tachiyomi or the decoders or even the YAML but thought it would be better to still post this.

Thanks

**Comment by inorichi** [comment]
This is a known problem in the decoders, not tachiyomi or the YAML parsers, and sadly I can't fix it.

This happens when images of a specific format are so big they need to be downsampled, and in older devices it's easier to reproduce. Colors may appear at a certain level of zoom (usually when the decoded region is 1:1 of the original image).

However, I'm surprised Image decodes the file only if it's not downloaded. Are you perhaps using a "custom directory" for downloads?

**Comment by ZorbaWas** [comment]
Thanks for the quick reply.

Do you mean, that by using a "higher performance" device it would possibly reduce or nullify this errors?

As for your question, no, the download path is the standart: 
sdcard/Tachiyomi/downloads/*source*/*comic*/*volume*

Soo do you think pre-downsampling (storing downsampled images instead of the originals) could be a answer?

**Comment by inorichi** [comment]
A better device might help, but only if yours isn't already reporting a max bitmap size of 4096x4096. Some old phones can't decode anything bigger than 2048x2048 and it downsamples earlier. 

Downscaling the image will surely help, but you could even keep the same resolution. The real problem is the format of the jpg images, though I don't know which specific setting causes the issues (colorspace, etc..). I guess they use a format with lower size but worse compatibility.

**Comment by ZorbaWas** [comment]
Ok thanks,
I am going to be poking around a bit when i have a little more free time, if you find anything about, why the "Image" decoder works when not downloaded or if you want to ask me anything else please do it.

**Comment by inorichi** [comment]
Well, I've fixed three bugs.

The first one, Skia and Rapid decoder names were inverted. They've been like this since I added Image some months ago. Not a major bug but shame on me. :sweat:

The second one, the image library SubsamplingScaleImageView converted an `Uri` back to a `File` when the path starts with `file://` and that fails when there are special characters. I've removed that in my fork. This bug was the one causing Image and Rapid (Skia in your description as per the previous bug) to fail when the chapter was downloaded. This will be available in the next release, in the meantime you can set your downloads directory to a custom one (you can select the same one you are using now), and it'll make the files load with `content://` instead of `file://`.

The last bug in RapidDecoder didn't allow me to reset the region decoder, making it behave incorrectly or not work at all. I had to fork the project and fix it.


As a side note, your device is reporting a max bitmap size of 2048. In my phone, Rapid (Skia in your description as per the first bug) decodes the image with colors, but it turns black and white after I zoom in. Anyways, this won't have a fix from my part, so just use Image because it'll work now.
