### ISSUE TITLE
Feature Request: Support for Dynasty Reader

### ISSUE THREAD

**Issue by igalic** [inorichi/tachiyomi#683]
I would like to see support for [Dynasty Reader](http://dynasty-scans.com/) added.

Looking at [other sources](https://github.com/inorichi/tachiyomi/tree/master/app/src/main/java/eu/kanade/tachiyomi/source/online/english) this seems to be "easy enough" that i could contribute it myself, however, i wouldn't know how to test it…

**Comment by inorichi** [comment]
It's not hard, but new catalog requests must go here: https://github.com/inorichi/tachiyomi-extensions
There's already one request open there btw.

About testing... well, compiling, trial and error. I want to write generic unit tests for that but there are a lot of other things to do and not so much time.

**Comment by igalic** [comment]
thank you very much for the pointer!
I didn't see (notice?) this linked in the CONTRIBUTING.md

re unit tests: any idea how?

**Comment by inorichi** [comment]
It was created recently and the current release doesn't support them. Also there are no downloads link yet.

You can run create and run tests with Robolectric. There are a few of them in this repository, you can use them as reference. Your tests would create an instance of the source and call all the `fetch*` methods, then do your checks/comparisons.

Keep in mind that all the `fetch*` methods are RxJava Observables, so instead of writing TestObservables (hard) you can call `.toBlocking().single()` to block the calls.
