### ISSUE TITLE
Metadata for local manga

### ISSUE THREAD

**Issue by shogunreaper** [inorichi/tachiyomi#698]
Can you add the ability to grab metadata for local manga, maybe by searching titles on sites?

i'd like to have the plot/genres and other stuff in my local manga as well.

**Comment by inorichi** [comment]
I won't code this. We discussed reading metadata from a file but decided not to include it since it's not critical. I can afford reading from a file since is easy (an external tool could generate them), but looking online is something I don't want to maintain here, at least yet.

Anyways, if anyone wants to implement this and it's not a lot of code, I will consider it.

**Comment by shogunreaper** [comment]
but shouldn't you just be able to use the same way that you grab information for any other manga?

**Comment by inorichi** [comment]
I grab that information from the url of the manga in the site. A local manga doesn't have an online url.

**Comment by wopian** [comment]
The metadata could potentially be populated via the tracker its synced to?

**Comment by shogunreaper** [comment]
well if it grabs the info by the url couldn't you just use that same url for the info?

like say if your folder is named naruto

it will search the manga sites for naruto the same way any other catalog searches (maybe with a popup if multiple hits come up) then just use the url you picked to grab the info.

**Comment by inorichi** [comment]
> The metadata could potentially be populated via the tracker its synced to?

That's feasible, but limited to english only.

> it will search the manga sites for naruto the same way any other catalog searches (maybe with a popup if multiple hits come up) then just use the url you picked to grab the info.

And that's what I don't want to (and won't) do.

**Comment by shogunreaper** [comment]
why not?

the only thing that needs to be maintained are what you are already maintaining for the other sites

**Comment by inorichi** [comment]
It's totally not the same. If you want, you can fork the repo and do it yourself.

**Comment by shogunreaper** [comment]
how is it not the same?

what else would need to be maintained?

**Comment by paronos** [comment]
There are a few ways to include metadata within `cbr/cbz` files. One option is to manage them like the covers (read a local file if present, otherwise try to read them from the first `cbz/cbr`).

The format that I found are (more info at http://www.denvog.com/comet/comet-specification/ and https://wiki.mobileread.com/wiki/CBR_and_CBZ#Metadata):
- CoMet (uses a CoMet.xml file)
- ComicRack (uses a ComicInfo.xml file)
- ComicBookLover (zip header)
- ComicBookInfo (zip header)
- Advanced Comic Book Format (xml)

The most popular format could be used (although I do not know which is between them)

**Comment by Moravuscz** [comment]
How about grabbing the info from MAL once you link it?

**Comment by fighuass** [comment]
Yeah, just grab the sypnosis from MAL.

**Comment by LakotaGray** [comment]
I'd also like to see the ability to add metadata to local manga. I'm of the opinion that since I'm taking the time to find, download, and then add to device so tachi can read the local manga, the metadata being entered by me is also fair. That way theres no need to try to sync or use tracking or online sites. If the one of the forms paranos mentioned is viable, it'd like be among the easier ways of incorporating it into tachi.

More than the description, my desire is to add either Artist/Author fields to enable the in library search feature to filter out local titles by author as well...

**Comment by null-von-sushi** [comment]
Just wanted to mention, I too think a (local, file based) approach would be great. Local Manga is, in my opinion, for a collection that you host yourself. Therefore it makes sense that you enter metadata yourself (otherwise why not just use any of the online plugins already built into tachiyomi). If someone thinks that writing tags manually each time is too much effort, they can just write a program to do it themselves 

For what it's worth, I would really love something like a 'category' or 'tag' feature in the 'Local Manga' catalogue if possible (like Kiss manga or manga fox have), though just being able to add arbitrary text to mangas without the search/filter option in the catalogue would be a huge improvement already I think.
