### ISSUE TITLE
Swap Between Sources

### ISSUE THREAD

**Issue by vampiricwulf** [inorichi/tachiyomi#776]
It would be nice if, while on a specific manga, you could quick search for their name on other sources. 

I specifically am asking for this because often I find that batoto will stop having updates for months at a time while other manga sites are still progressing by the usual schedule. I would never know if I didn't search them out myself. 

Version: v5. 1

**Comment by Psoplayer89** [comment]
My request is along these lines as well so I don't know that it's worth opening another request but it would be awesome if once the manga is in your library it's not "bound" to the source you got it from first. Being able to click on the thumbnail then choosing the source to pull from in the library would be way easier and leave a much cleaner library to not have 4 different Berserk thumbnails because x site was down so I had to go to y site, pick it and figure out where I stopped. If that makes no sense or is just ridiculous sorry to waste your time. If that's somehow possible already then I'm just an idiot....

**Comment by j2ghz** [comment]
@Psoplayer89 #886 #1041

**Comment by Psoplayer89** [comment]
Damn, sorry to waste your time I thought I had checked everywhere to see if it had been brought up before. Kinda thought the only way to do it was basically redo the library system, not a coder though so I was hoping there was a simple solution. So sorry to waste your time :/

**Comment by niknetniko** [comment]
With batoto closing down, this would be even handier to migrate series to other sites without doing it all manually

**Comment by cd0rw0** [comment]
Guys refer here #1156

**Comment by arkon** [comment]
Source migration exists now.
