### ISSUE TITLE
[Feature request] Options to include in backup

### ISSUE THREAD

**Issue by eji30** [inorichi/tachiyomi#795]
I know this things are already available options in backup as of v0.5.2: Manga, Categories, Chapters, Tracking, History
I hope these things get added too:
1. Tachiyomi settings itself - General setting, Reader, Downloads, etc...
2. Manga cover picture - I like searching and downloading anime folder icons and those are what I use as cover for my lists in Tachiyomi. If I have so many on my list, it will be hard to redo it all over again so it would be nice if it is also included in backups.
3. [optional] Logins - Batoto, MAL, etc...

Background info:
I just backed up Tachiyomi an hour ago because my version was downloaded from F-Droid, then I downloaded the GitHub version (for the auto-update feature). Then when I restored my recent backup, these 3 things above where what I repeated setting up. Hope these will be implemented in a future version. Thank you so much!

Version: v0.5.2

**Comment by inorichi** [comment]
1. We didn't want to add an extra compatibility layer. We often need to change something and this would be troublesome for us. Furthermore, some of them like the selected downloads directory, can't be recovered from a backup (because Google).

2. You can just make a backup of the directory. It's in `/sdcard/Android/data/eu.kanade.tachiyomi`. That folder is deleted with the app, so you need to move it somewhere else before uninstalling, and then move it again where it was after installing the new one.

3. No. I won't store those.

**Comment by eji30** [comment]
Actually folder is not deleted with the app, that's what happened to me when I uninstalled. Anyways, I guess I'm stuck on manually doing these. Thanks anyways!
