### ISSUE TITLE
Corrupted Images after upgrading to the Android O beta

### ISSUE THREAD

**Issue by AbusiveTruck** [inorichi/tachiyomi#802]
I opted into the Android O beta yesterday, and when I opened tachiyomi everything seemed fine until I actually started trying to read a comic. The top part of 80% of my pages look like they are smeared. It didn't seem to matter if it was issues I had downloaded or if I viewed them directly. 
This is my first time submitting an issue, so I'm not sure what the preferred method of including an image of the issue is. Are imgur links allowed?

Version: v0.5.2
Android O OPP2.170420.017 Pixel XL

**Comment by wopian** [comment]
>This is my first time submitting an issue, so I'm not sure what the preferred method of including an image of the issue is. Are imgur links allowed?

Uploading an image to imgur and linking it here (`![](https://imgurlinkhere.png)` is ideal 😄

**Comment by AbusiveTruck** [comment]
![](http://i.imgur.com/YTSypaO.jpg)
![](http://i.imgur.com/wN0rPlP.jpg)

**Comment by inorichi** [comment]
Try with another image decoder.

**Comment by AbusiveTruck** [comment]
I tried all three options and they all produced the exact same result.

**Comment by inorichi** [comment]
Well `¯\_(ツ)_/¯`. It might have to do with how subsampling draws a bitmap in the canvas, but it looks like a bug in AOSP, I wouldn't be surprised given that O is still a WIP. Try with [this demo app](https://play.google.com/store/apps/details?id=com.davemorrissey.labs.subscaleview.sample).

Also, do you have crop borders enabled?

**Comment by NoodleMage** [comment]
It's the crop borders function. On Android O without works fine, with borders cropped enabled same result as in picture.

**Comment by inorichi** [comment]
That makes sense. I'll work on a fix once O is released (if it's still an issue). The bitmap reconfigure method may need a different input.

**Comment by libjared** [comment]
I just upgraded to Oreo (which was released as stable for Google Pixels yesterday) and got bit by this bug. Some facts:
- Changing image decoder does nothing
- Disabling border crop fixes it
- Some images display okay, since they don't have any borders to crop (color-scanned volume covers, flashback chapters with black backgrounds)

Example:
![Good](https://i.imgur.com/8GqLo6F.png)
![Bad](https://i.imgur.com/LGmHNS4.png)

Visually, it looks as if the image data was copied from one place to another without regard to source/destination image width. I also noticed how much of the bottom is left unglitched is proportional to how much border was cropped. And, if there's a page where `width == croppedWidth` but `height >= croppedHeight`, the image is fine until the bottom, where the last few rows of pixels are doubled. So essentially, it's as if the destination image buffer uses the source's dimensions rather than the new, cropped ones.

**Comment by null-dev** [comment]
@libjared What version are you running. Crop borders has been fixed for Android O in the latest dev build but the fix is not in the latest release yet. If you are running the release build try installing the dev build and see if it fixes the issue.

**Comment by libjared** [comment]
You're right that I was on stable 0.6.1. I expected to see some mention about the fix in this or the other issue. Installing dev build has historically been a PITA, though I apologize for not trying that first.
