### ISSUE TITLE
Pause/Cancel download queue separate item

### ISSUE THREAD

**Issue by ThangBK2009** [inorichi/tachiyomi#809]
Sometime I want to remove few item, But I only pause or remove all.

Remove line above and describe your issue here. Fill out version below. Use Preview.

Version: r000 or v0.0.0
(other relevant info like OS)

**Comment by Jerrk** [comment]
i ran into an issues today where i downloaded a chapter and before it was finished it was deleted from the source. this made it so i couldnt remove it from the source since it was deleted, and i couldnt unmark/mark the manga to delete the removed downloaded chapter since it hadn't finished downloading.

this chapter was stuck at the top of my download queue and there was nothing i could do to remove it except for clearing the entire queue - losing about 200 queued items in the process.

it baffles me this hasn't been fixed yet.

**Comment by arkon** [comment]
Added in fb897e37d1a0f68355bccbbfd22a91813906b5b5
