### ISSUE TITLE
Automatic backup does not seem to be working properly

### ISSUE THREAD

**Issue by emyarod** [inorichi/tachiyomi#900]
Version: 0.6.1
Android version: 7.1.2
Device: Google Pixel XL, (also tested on Samsung Galaxy S8+, Google Nexus 7 (2013), Amazon Fire 8 (7th gen))

I have enabled automatic library backups, but no files are being written to the specified backup directory. Not sure how else to troubleshoot the problem. Please let me know if there is any additional information I can provide to help!

**Comment by cd0rw0** [comment]
Version: 0.6.1
Android version: 7.1.2
Device: Samsung S3 ( Resurrection remix Rom)

Yap, 
im having same issue i thought it was my phone, so i reformat. still have same issue. 

my setup 
backup - daily or every 2 days 
location - sdcard
max backup - 3

**Comment by Pizz001** [comment]
i've also posted about this  in the past and was given a work around , but
i'm having more problem with it just hanging yet again, i can back it up to
dropbox so i can share  to my phone so i can keep the same manga synced
between the 2 , please deal with this as twisting the tablet to side view
and then using the back up , doesn't seem to work anymore at all
also adding a reset of the default back path would be good
could someone please deal with this as for 3 week's i've not been able to
back up and in the version before 5.2 i never had one finish :(


Elliott Bechtol

Sent from googlemail
via phone or desktop

**Comment by emyarod** [comment]
Any updates on this?

**Comment by dobbleg1000** [comment]
Does anyone have any word on this?

**Comment by emyarod** [comment]
still not working for me in 0.6.3, Android 8.0.0

**Comment by tippl** [comment]
Any update on this? Came across a bug that completely corrupted the app data, and found out my last backup was months ago.

**Comment by mrskizzex** [comment]
Doesn't work in r1272 Android 7.1.2 either. 
@tippl and anyone in this thread I can only recommend titanium backup.

**Comment by j2ghz** [comment]
@mrskizzex You should always mention that it requires root, so not an option for most people.

**Comment by mrskizzex** [comment]
@j2ghz Sorry, sometimes i forget that it's not a common practice to root your phone.

**Comment by N0153** [comment]
I confirm that this feature still does not work. I tried using both internal and external memory and pretty much every backup frequency and max automatic backups. 

My setup:
- Devices: Huawei P9 Lite (VNS-L31C432), LG G Pad 8.3 (LG-V500) 
- OS versions: official ROM Android 7.0, Lineage 14.1 ROM Android 7.1.2
- Rooted devices
- Tachiyomi v0.6.3

**Comment by emyarod** [comment]
it looks like this is still broken on 0.6.4

hoping that #1074 fixes everything!

**Comment by NoodleMage** [comment]
Hopefully misclicked. Please let me know if this fixes the issue ;)

**Comment by emyarod** [comment]
@NoodleMage is this change in the dev release or would I have to build from master?

**Comment by NoodleMage** [comment]
Should be in dev

**Comment by emyarod** [comment]
did not seem to be working for me when I downloaded dev release yesterday, but I will keep trying today

**Comment by N0153** [comment]
The feature is now working properly on the latest (stable) build.
Keep up the good work!

**Comment by tippl** [comment]
Weird, doesn't seem to be working for me.
Android 8.0.0 OPD1.170816.025
Pixel 2
Updated to the lastest stable version: 0.6.5
Set up max automatic backups of 5, and interval of 6 hours.

After few days i noticed it didn't even create the new automatic folder so i created it manually, but alas few days later it is still empty.

**Comment by tippl** [comment]
So, few days of testing later. (if you could call it testing, with 6 hours between backups there are only few times for it to happen)

Backup settings:
Path: default - /sdcard/Tachiyomi/backup/automatic - the folder exists
Frequency: 6 hours
Max 5 backups

Before i wrote the previous comment, i had version 0.6.5 for about 4 days. After about 2 days i manually created the backup folder, despite this it still didn't backup. Now i had some manual backups in the level above (/sdcard/Tachiyomi/backup), after moving them away the automatic folder started being populated by automatic backups. (not sure though if caused by me removing the manual backups or just being unlucky, can't tell in this short timeframe)

For the past ~3 days tachiyomi has been backing up, but i couldn't say that launching of the backup task is reliable. (see screenshot of backup folder after ~3 days, along with current date and time) It more resembles rolling a die every 6 hours to see if we backup today.

Screenshot:
![screenshot_20171206-200105](https://user-images.githubusercontent.com/2827500/33680993-95b7f0e4-dac3-11e7-8948-d5697e518330.png)
