### ISSUE TITLE
Malformed[1] for local sources

### ISSUE THREAD

**Issue by uenoshita** [inorichi/tachiyomi#905]
After restoring a backup when I try to view local sources I get Malformed [1]. I've tried switching from sdcard to internal storage and deleting the previous local manga from my library and try to add it but nothing works.

Version: r1188
(other relevant info like OS)
OS: LineageOS 14.1
Phone Redmi Note 3 Pro (kenzo)

**Comment by raymoo** [comment]
This happens to me too.

**Comment by kfdz277** [comment]
very very very late to this but the issue is having non-standard characters in the name of a folder inside the .zip (and similar archive file types) of your local manga. mine had japanese characters in it and all you have to do is make the folder name regular latin characters on a us keyboard and itll work

**Comment by raymoo** [comment]
Probably would work to reencode them in utf8 with the original titles too

**Comment by afilip1** [comment]
Hi, I primarily read raw manga and have encountered this problem when trying to use Tachiyomi as well. Is there any chance this issue might get fixed? Renaming is not an option for me because in my sources every single page image has Japanese characters in its name. Thanks.

**Comment by arkon** [comment]
Could you upload a sample file? Can send it via Discord if you don't want to post it publicly.

**Comment by afilip1** [comment]
On further investigation, it seems that unpacking and then repacking the zip file with 7zip also fixes the issue... Not sure what it might be caused by (character encoding shenanigans?), but looks like the problem is largely on my end then, apologies for the ruckus. I can provide a sample file through Discord if you'd like to investigate further, just let me know how I can contact you if so.

**Comment by arkon** [comment]
Feel free to ping or DM me on Discord (@arkon#4275).

**Comment by Ksetrar** [comment]
Why not moved into close section ? Github Bug [Label]

**Comment by arkon** [comment]
I think it's still an issue?

**Comment by Ksetrar** [comment]
Nag, you already have solve dit

**Comment by arkon** [comment]
Why do you say that?
