### ISSUE TITLE
[BUG] Downloaded chapters numbers shows  -1

### ISSUE THREAD

**Issue by 444nonymous** [inorichi/tachiyomi#914]
I have a problem with some mangas. Like "One Outs" in Kissmanga. All chapters from 1 to 130 are listed as -1.

Sorting options don't matter. But they are listed and sorted in order. The problem is all chapters are named "-1".

Probably related to https://github.com/inorichi/tachiyomi/issues/894

**Comment by j2ghz** [comment]
## Online sources
For online sources sort by source is available. That option is superior to any sorting Tachiyomi could do, so that is the default. You should always be using "Display mode > Show Title" and "Sorting mode > By Source". Don't use "Show chapter number", it is not intended to be used in this way. If with "sort by source" the order of the chapters is wrong, compare the order with their webisite, because it could be a problem on their side.

## Local sources
For local sources the option to sort by source doesn't really make sense, so here you should use "Sorting mode > By Chapter Number". You can use "Display mode > Show Chapter numbers" to see the parsed numbers, and if they are wrong, you can report it.

**Comment by 444nonymous** [comment]
No.  Show Chapter numbers always shows -1 for every chapter from 1 to 130. 

No other option changes that. So it's a bug. Try it by yourself. Download some chapters.

**Comment by NoodleMage** [comment]
It's not really a bug. It's a flaw in the chapter recognition  If it can't recognize the chapter it will return -1.

 In this case its an mistake in the regex. Will pick it up when I have some time.
