### ISSUE TITLE
Compress (ZIP / RAR / 7z) mangas to avoid Android performance problems.

### ISSUE THREAD

**Issue by 444nonymous** [inorichi/tachiyomi#918]
I know this has been requested in the past and has been considered to be implemented in the future.

As a feature, having mangas zipped by chapters (or one zip per manga with subfolders per chapters) is not a priority. It's a great feature for archiving purposes and collecting / sorting mangas, but not intermediately necessary.

On the other hand I have real problems with my phone. It took me a while to understand that they were caused by Tachiyomi. It's a 2016 Samsung A5, 8 cores, 2GB RAM. I was experiencing very slow boots and some apps did not load or gave error at startup. So I had to reboot.

It's caused by the memory card. Sandisk original (Amazon), brand new and fast, it can record video at the highest resolution. I only keep like 20-30 mangas at most, but they have +100.000 individual jpg files. Even if all folders are with .nomedia to avoid any problems, it takes a lot of time to mount the memory card. And I don't even have any app running from the card. The phone just hangs for a lot of time when mounting it.

So please, reconsider the zip feature as a priority to avoid performance issues. My phone boots in 30 seconds with a full memory card with a few files (large videos). But it takes minutes and reboots with a mostly empty card with tens of thousands of files. Since Tachiyomi is going to download so many files, I think it's necessary to store them. Any fast no-compression storage file format would do, after all jpeg is already compressed, so no cpu processing or delay in storing / accesing manga images.

Thanks!

**Comment by inorichi** [comment]
It shouldn't be too difficult to add an option to compress everything. However, I think only zip will be supported. Rar compression is propietary and requires written permission from its creator, and 7z is not very popular.

**Comment by 444nonymous** [comment]
I think zip with minimal o no compression (store option) would do. Fastest to store and read and less CPU load.  It would be a waste trying to re-compress image formats like jpg. With ultra compression options in rar5 and 7z you can get a 20% size reduction. Normal zip is even worse.

A good option would be to download and store by chapters. Since that's how Tachiyomi works.
NOW: /Mangas/Dragon Ball/Chapter 1/image1.jpg, image2.jpg, etc.
ZIP: /Mangas/Dragon Ball/Chapter1.cbz, Chapter2.cbz, etc.

Some people asked for an option to store and compress the whole manga. That could be a manual option. The problem with creating one file per manga "Dragon Ball.cbz" and storing chapters as folders inside, is file fragmentation and CPU load re-compressing the same big file every time a chapter is added. It also takes more time to open a single file with thousands of files (slow reading).  But it could be added as a one time action for finished mangas, merging all Chapter.cbz files in one big Manga.cbz.

**Comment by inorichi** [comment]
There will only be per chapter compression. A single zip to store an entire series is troublesome to handle.

I'll do a few performance/size tests but most probably they won't be compressed (store).

I'm not sure about the file extension though. Zip, cbz, or add an option to let the user select one, but it would look like a stupid setting from my point of view.

**Comment by 444nonymous** [comment]
No need to add an option. I think cbz is better because it would be only picked by reader apps. Zips are listed as archive files by the file managers in Android. Even with .nomedia Android storage manager scans everything and you get the % of used space as: 1GB images, 200MB Docs, etc. Cbz is "other files" and it makes more sense.

The only question is hot to handle the transition when you already have downloaded chapters with images in folders. Are these going to be stored in the new format? It could take a lot of time.

**Comment by inorichi** [comment]
It'll be a switch in the downloads settings, so it'll only apply to new downloads. It shouldn't be hard to find a tool to automate the process if you want them as zip.

Sadly I don't know when all of this will be available, I need to rewrite part of the reader to support it. In fact I want to write the reader from scratch with better chapter transitions and responsiveness, but I have yet to find the time and motivation (it's not easy) to start.

**Comment by Efreak** [comment]
Tar might solve the issue of recompressing etc. I don't know a while lot about it, but I do know that the command line has an option for concatenation of two tar files, as well as another option for extracting files from an archive that was created by `cat`ing two files together; supposedly the only difference is that the archive-end marker is a series of zeroes. You could tar the new chapters together, then append the new file to the old; this would negate the need to recreate the archive entirely.

For more info, see the bottom of [here](https://www.gnu.org/software/tar/manual/html_node/concatenate.html).

I use tar personally, but that's only because I'm too lazy to find the no-compression option in the terminal every time. Zip still has the advantage of being easier to work with when using Windows, since it has native support.

**Comment by bmix** [comment]
Having *Tachiyomi* create CBZ files automatically would be the biggest feature wish I have! :-)

Convention is to use one archive per comic book issue. For paperback editions this can mean huge files, but since we consume the comics from the web, and the sites keep them issued by release, it should fully suffice to have one CBZ archive per such issue/chapter. Just store the images from each folder in an archive with the series name, the issue number and the, eventually available, chapter number. It does not make sense to compress already compressed images. So something like '`001 - Series Name - Chapter Name.cbz`'.

I would stick to the convention of suffixing a ComicBook Archive in ZIP format with `*.cbz` and save myself the additional work of supporting any other archives. It's easy and quick to convert one arc format into another, these days, on a desktop or NAS.

It would be nice, to have, at least basic, metadata in the form of '`ComicInfo.xml`' from [Meta Data in Comic Files - ComicRack](http://comicrack.cyolito.com/software/windows/windows-documentation/7-meta-data-in-comic-files). It should be as easy as:

```xml
<ComicInfo>
 <Title>Chapter Name</Title>
 <Series>Series Name</Series>
 <Number>Number of issue in sequence</Number>
</ComicInfo>
```

If you want to, you could also add the spine of pages like
```xml
<ComicInfo>
 <Title>Chapter Name</Title>
 <Series>Series Name</Series>
 <Number>Number of issue in sequence</Number>
 <Pages>
  <Page Image="0" ImageSize="656731" ImageWidth="1424" ImageHeight="2190"/>
  <Page Image="1" ImageSize="438566" ImageWidth="1424" ImageHeight="2190" />
  <Page Image="2" ImageSize="479301" ImageWidth="1424" ImageHeight="2190" />
 </Pages>
</ComicInfo>
```
Depending on how much metadata you want to scrape on those pages, you could fill in more, obviously. But since collectors use usually a *ComicVine* scraper to refine their collections, it may be enough to have title, series and issue-number stored. The `ComicInfo.xml` goes, along with all the pictures, into the root of the archive.

Software currently supporting `ComicInfo.xml`:

* [KCC (a.k.a. Kindle Comic Converter) is a comic and manga converter for ebook readers.](https://github.com/ciromattia/kcc)
* [ComicRack](http://comicrack.cyolito.com/)
* [ComicTagger](https://code.google.com/p/comictagger/)
* [ComicInfo Editor](https://archive.codeplex.com/?p=comicinfoeditor)
* [Ubooquity](http://vaemendis.net/ubooquity/)
* [Calibre Metadata Writer Plugin - Embed Comic Metadata](http://www.mobileread.mobi/forums/showthread.php?t=264710)
* maybe others

**Comment by ZaneHannanAU** [comment]
Personally I would also use tar (well, cbt); but would be using an index file for the information.
For  the reader, if we could add the option to reencode excessively large or otherwise oversized images (eg through libwebp, and/or through reslicing of images with the webtoon reader) that could become useful in terms of memory management, however more client side work would be required.

Apart from that, parallel downloads across different sources?

This would become its own fr at that point.

**Comment by Efreak** [comment]
Even if the UI for creating cbz files is unimplemented, since Tachiyomi already supports local CBZ files, it would be nice if it supported viewing downloaded chapters in the original chapter folder that have been manually converted into cbz files. (`/sdcard/Tachiyomi/downloads/SOURCE/TITLE/CHAPTER.cbz` instead of `/sdcard/Tachiyomi/local/SOURCE - TITLE/CHAPTER.cbz`)

For example, I often run [this script](https://gist.github.com/Efreak/75da094f0877f8fe34d55767c443a574) in a manga folder using termux, to create a cbz for each chapter, either to reduce the number of files, or to read with another device/app. This has issues with reading in chapter order, though, since Tachiyomi doesn't expose the correct reading order - sorting by folder modification date doesn't work when network errors occurred, placing chapters out of order. Also, Android doesn't allow changing/setting file modification dates, so if your file manager copies in order by name, then your modification date order is the same (I believe most file managers do this).

If Tachiyomi supported keeping the CBZ in the original location (`/sdcard/Tachiyomi/downloads/SOURCE/TITLE/CHAPTER.cbz`), it would be much nicer: I could keep the chapters associated with the source this way, know which were/not downloaded without checking another title first, and I wouldn't have to first rename every chapter/folder to keep them in order

**Comment by arkon** [comment]
https://github.com/tachiyomiorg/android-app/issues/10
